-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_object_green_classification_hls_object_green_classification_Pipeline_InitLoop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    parent_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    parent_ce1 : OUT STD_LOGIC;
    parent_we1 : OUT STD_LOGIC;
    parent_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    min_x_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_x_ce1 : OUT STD_LOGIC;
    min_x_we1 : OUT STD_LOGIC;
    min_x_d1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_x_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_x_ce1 : OUT STD_LOGIC;
    max_x_we1 : OUT STD_LOGIC;
    max_x_d1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_y_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_y_ce1 : OUT STD_LOGIC;
    min_y_we1 : OUT STD_LOGIC;
    min_y_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    max_y_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_y_ce1 : OUT STD_LOGIC;
    max_y_we1 : OUT STD_LOGIC;
    max_y_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_is_green_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    center_is_green_ce1 : OUT STD_LOGIC;
    center_is_green_we1 : OUT STD_LOGIC;
    center_is_green_d1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of hls_object_green_classification_hls_object_green_classification_Pipeline_InitLoop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv9_140 : STD_LOGIC_VECTOR (8 downto 0) := "101000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln109_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln109_fu_185_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_54 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_5_fu_179_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln112_fu_195_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hls_object_green_classification_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component hls_object_green_classification_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if ((icmp_ln109_fu_173_p2 = ap_const_lv1_0)) then 
                    i_fu_54 <= i_5_fu_179_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_54 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln109_fu_173_p2, ap_start_int)
    begin
        if (((icmp_ln109_fu_173_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_state1, i_fu_54, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_54;
        end if; 
    end process;

    center_is_green_address1 <= zext_ln109_fu_185_p1(9 - 1 downto 0);

    center_is_green_ce1_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            center_is_green_ce1 <= ap_const_logic_1;
        else 
            center_is_green_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    center_is_green_d1 <= ap_const_lv1_0;

    center_is_green_we1_assign_proc : process(ap_CS_fsm_state1, icmp_ln109_fu_173_p2, ap_start_int)
    begin
        if (((icmp_ln109_fu_173_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            center_is_green_we1 <= ap_const_logic_1;
        else 
            center_is_green_we1 <= ap_const_logic_0;
        end if; 
    end process;

    i_5_fu_179_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv10_1));
    icmp_ln109_fu_173_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv10_200) else "0";
    max_x_address1 <= zext_ln109_fu_185_p1(9 - 1 downto 0);

    max_x_ce1_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            max_x_ce1 <= ap_const_logic_1;
        else 
            max_x_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    max_x_d1 <= ap_const_lv9_0;

    max_x_we1_assign_proc : process(ap_CS_fsm_state1, icmp_ln109_fu_173_p2, ap_start_int)
    begin
        if (((icmp_ln109_fu_173_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            max_x_we1 <= ap_const_logic_1;
        else 
            max_x_we1 <= ap_const_logic_0;
        end if; 
    end process;

    max_y_address1 <= zext_ln109_fu_185_p1(9 - 1 downto 0);

    max_y_ce1_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            max_y_ce1 <= ap_const_logic_1;
        else 
            max_y_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    max_y_d1 <= ap_const_lv8_0;

    max_y_we1_assign_proc : process(ap_CS_fsm_state1, icmp_ln109_fu_173_p2, ap_start_int)
    begin
        if (((icmp_ln109_fu_173_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            max_y_we1 <= ap_const_logic_1;
        else 
            max_y_we1 <= ap_const_logic_0;
        end if; 
    end process;

    min_x_address1 <= zext_ln109_fu_185_p1(9 - 1 downto 0);

    min_x_ce1_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            min_x_ce1 <= ap_const_logic_1;
        else 
            min_x_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    min_x_d1 <= ap_const_lv9_140;

    min_x_we1_assign_proc : process(ap_CS_fsm_state1, icmp_ln109_fu_173_p2, ap_start_int)
    begin
        if (((icmp_ln109_fu_173_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            min_x_we1 <= ap_const_logic_1;
        else 
            min_x_we1 <= ap_const_logic_0;
        end if; 
    end process;

    min_y_address1 <= zext_ln109_fu_185_p1(9 - 1 downto 0);

    min_y_ce1_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            min_y_ce1 <= ap_const_logic_1;
        else 
            min_y_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    min_y_d1 <= ap_const_lv8_F0;

    min_y_we1_assign_proc : process(ap_CS_fsm_state1, icmp_ln109_fu_173_p2, ap_start_int)
    begin
        if (((icmp_ln109_fu_173_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            min_y_we1 <= ap_const_logic_1;
        else 
            min_y_we1 <= ap_const_logic_0;
        end if; 
    end process;

    parent_address1 <= zext_ln109_fu_185_p1(9 - 1 downto 0);

    parent_ce1_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            parent_ce1 <= ap_const_logic_1;
        else 
            parent_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    parent_d1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln112_fu_195_p1),16));

    parent_we1_assign_proc : process(ap_CS_fsm_state1, icmp_ln109_fu_173_p2, ap_start_int)
    begin
        if (((icmp_ln109_fu_173_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            parent_we1 <= ap_const_logic_1;
        else 
            parent_we1 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln112_fu_195_p1 <= ap_sig_allocacmp_i_4(9 - 1 downto 0);
    zext_ln109_fu_185_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_4),64));
end behav;
