// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hls_object_green_classification_hls_object_green_classification_Pipeline_PASS_3_5_2_in (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        next_label_5,
        i_5,
        min_x_load_1,
        max_x_load_1,
        min_y_load_1,
        max_y_load,
        parent_address0,
        parent_ce0,
        parent_q0,
        min_x_address0,
        min_x_ce0,
        min_x_q0,
        max_x_address0,
        max_x_ce0,
        max_x_q0,
        min_y_address0,
        min_y_ce0,
        min_y_q0,
        max_y_address0,
        max_y_ce0,
        max_y_q0,
        is_external_address1,
        is_external_ce1,
        is_external_we1,
        is_external_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] next_label_5;
input  [15:0] i_5;
input  [8:0] min_x_load_1;
input  [8:0] max_x_load_1;
input  [7:0] min_y_load_1;
input  [7:0] max_y_load;
output  [8:0] parent_address0;
output   parent_ce0;
input  [15:0] parent_q0;
output  [8:0] min_x_address0;
output   min_x_ce0;
input  [8:0] min_x_q0;
output  [8:0] max_x_address0;
output   max_x_ce0;
input  [8:0] max_x_q0;
output  [8:0] min_y_address0;
output   min_y_ce0;
input  [7:0] min_y_q0;
output  [8:0] max_y_address0;
output   max_y_ce0;
input  [7:0] max_y_q0;
output  [8:0] is_external_address1;
output   is_external_ce1;
output   is_external_we1;
output  [0:0] is_external_d1;

reg ap_idle;
reg parent_ce0;
reg min_x_ce0;
reg max_x_ce0;
reg min_y_ce0;
reg max_y_ce0;
reg is_external_ce1;
reg is_external_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln261_fu_195_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] j_1_reg_280;
wire   [63:0] zext_ln261_fu_201_p1;
reg   [63:0] zext_ln261_reg_289;
reg   [63:0] zext_ln261_reg_289_pp0_iter1_reg;
reg   [63:0] zext_ln261_reg_289_pp0_iter2_reg;
reg   [63:0] zext_ln261_reg_289_pp0_iter3_reg;
reg   [63:0] zext_ln261_reg_289_pp0_iter4_reg;
reg   [63:0] zext_ln261_reg_289_pp0_iter5_reg;
wire   [0:0] icmp_ln263_1_fu_206_p2;
reg   [0:0] icmp_ln263_1_reg_303;
wire   [0:0] and_ln263_fu_228_p2;
reg   [0:0] and_ln263_reg_308;
reg   [0:0] and_ln263_reg_308_pp0_iter2_reg;
reg   [0:0] and_ln263_reg_308_pp0_iter3_reg;
reg   [0:0] and_ln263_reg_308_pp0_iter4_reg;
reg   [0:0] and_ln263_reg_308_pp0_iter5_reg;
wire   [0:0] icmp_ln265_fu_233_p2;
reg   [0:0] icmp_ln265_reg_317;
reg   [0:0] icmp_ln265_reg_317_pp0_iter3_reg;
reg   [0:0] icmp_ln265_reg_317_pp0_iter4_reg;
reg   [0:0] icmp_ln265_reg_317_pp0_iter5_reg;
wire   [0:0] icmp_ln265_1_fu_238_p2;
reg   [0:0] icmp_ln265_1_reg_326;
reg   [0:0] icmp_ln265_1_reg_326_pp0_iter4_reg;
reg   [0:0] icmp_ln265_1_reg_326_pp0_iter5_reg;
wire   [0:0] icmp_ln266_fu_243_p2;
reg   [0:0] icmp_ln266_reg_335;
reg   [0:0] icmp_ln266_reg_335_pp0_iter5_reg;
wire   [0:0] inside_fu_248_p2;
reg   [0:0] inside_reg_344;
wire    ap_block_pp0_stage0;
reg   [15:0] j_fu_64;
wire   [15:0] add_ln261_fu_212_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_j_1;
wire   [0:0] icmp_ln263_fu_223_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
end

hls_object_green_classification_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln261_fu_195_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_64 <= add_ln261_fu_212_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_64 <= 16'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln263_reg_308 <= and_ln263_fu_228_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        j_1_reg_280 <= ap_sig_allocacmp_j_1;
        zext_ln261_reg_289_pp0_iter1_reg[15 : 0] <= zext_ln261_reg_289[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln263_reg_308_pp0_iter2_reg <= and_ln263_reg_308;
        and_ln263_reg_308_pp0_iter3_reg <= and_ln263_reg_308_pp0_iter2_reg;
        and_ln263_reg_308_pp0_iter4_reg <= and_ln263_reg_308_pp0_iter3_reg;
        and_ln263_reg_308_pp0_iter5_reg <= and_ln263_reg_308_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln265_1_reg_326_pp0_iter4_reg <= icmp_ln265_1_reg_326;
        icmp_ln265_1_reg_326_pp0_iter5_reg <= icmp_ln265_1_reg_326_pp0_iter4_reg;
        icmp_ln265_reg_317_pp0_iter3_reg <= icmp_ln265_reg_317;
        icmp_ln265_reg_317_pp0_iter4_reg <= icmp_ln265_reg_317_pp0_iter3_reg;
        icmp_ln265_reg_317_pp0_iter5_reg <= icmp_ln265_reg_317_pp0_iter4_reg;
        icmp_ln266_reg_335_pp0_iter5_reg <= icmp_ln266_reg_335;
        zext_ln261_reg_289_pp0_iter2_reg[15 : 0] <= zext_ln261_reg_289_pp0_iter1_reg[15 : 0];
        zext_ln261_reg_289_pp0_iter3_reg[15 : 0] <= zext_ln261_reg_289_pp0_iter2_reg[15 : 0];
        zext_ln261_reg_289_pp0_iter4_reg[15 : 0] <= zext_ln261_reg_289_pp0_iter3_reg[15 : 0];
        zext_ln261_reg_289_pp0_iter5_reg[15 : 0] <= zext_ln261_reg_289_pp0_iter4_reg[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln261_fu_195_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln263_1_reg_303 <= icmp_ln263_1_fu_206_p2;
        zext_ln261_reg_289[15 : 0] <= zext_ln261_fu_201_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln263_reg_308_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln265_reg_317 == 1'd1))) begin
        icmp_ln265_1_reg_326 <= icmp_ln265_1_fu_238_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln263_reg_308) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln265_reg_317 <= icmp_ln265_fu_233_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln263_reg_308_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln265_1_reg_326 == 1'd1) & (icmp_ln265_reg_317_pp0_iter3_reg == 1'd1))) begin
        icmp_ln266_reg_335 <= icmp_ln266_fu_243_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln263_reg_308_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln266_reg_335 == 1'd1) & (icmp_ln265_1_reg_326_pp0_iter4_reg == 1'd1) & (icmp_ln265_reg_317_pp0_iter4_reg == 1'd1))) begin
        inside_reg_344 <= inside_fu_248_p2;
    end
end

always @ (*) begin
    if (((icmp_ln261_fu_195_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 16'd1;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        is_external_ce1 = 1'b1;
    end else begin
        is_external_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln263_reg_308_pp0_iter5_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (inside_reg_344 == 1'd1) & (icmp_ln266_reg_335_pp0_iter5_reg == 1'd1) & (icmp_ln265_1_reg_326_pp0_iter5_reg == 1'd1) & (icmp_ln265_reg_317_pp0_iter5_reg == 1'd1))) begin
        is_external_we1 = 1'b1;
    end else begin
        is_external_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        max_x_ce0 = 1'b1;
    end else begin
        max_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        max_y_ce0 = 1'b1;
    end else begin
        max_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        min_x_ce0 = 1'b1;
    end else begin
        min_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        min_y_ce0 = 1'b1;
    end else begin
        min_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        parent_ce0 = 1'b1;
    end else begin
        parent_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln261_fu_212_p2 = (ap_sig_allocacmp_j_1 + 16'd1);

assign and_ln263_fu_228_p2 = (icmp_ln263_fu_223_p2 & icmp_ln263_1_reg_303);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln261_fu_195_p2 = ((ap_sig_allocacmp_j_1 == next_label_5) ? 1'b1 : 1'b0);

assign icmp_ln263_1_fu_206_p2 = ((i_5 != ap_sig_allocacmp_j_1) ? 1'b1 : 1'b0);

assign icmp_ln263_fu_223_p2 = ((j_1_reg_280 == parent_q0) ? 1'b1 : 1'b0);

assign icmp_ln265_1_fu_238_p2 = ((max_x_q0 < max_x_load_1) ? 1'b1 : 1'b0);

assign icmp_ln265_fu_233_p2 = ((min_x_q0 > min_x_load_1) ? 1'b1 : 1'b0);

assign icmp_ln266_fu_243_p2 = ((min_y_q0 > min_y_load_1) ? 1'b1 : 1'b0);

assign inside_fu_248_p2 = ((max_y_q0 < max_y_load) ? 1'b1 : 1'b0);

assign is_external_address1 = zext_ln261_reg_289_pp0_iter5_reg;

assign is_external_d1 = 1'd0;

assign max_x_address0 = zext_ln261_reg_289_pp0_iter1_reg;

assign max_y_address0 = zext_ln261_reg_289_pp0_iter3_reg;

assign min_x_address0 = zext_ln261_reg_289;

assign min_y_address0 = zext_ln261_reg_289_pp0_iter2_reg;

assign parent_address0 = zext_ln261_fu_201_p1;

assign zext_ln261_fu_201_p1 = ap_sig_allocacmp_j_1;

always @ (posedge ap_clk) begin
    zext_ln261_reg_289[63:16] <= 48'b000000000000000000000000000000000000000000000000;
    zext_ln261_reg_289_pp0_iter1_reg[63:16] <= 48'b000000000000000000000000000000000000000000000000;
    zext_ln261_reg_289_pp0_iter2_reg[63:16] <= 48'b000000000000000000000000000000000000000000000000;
    zext_ln261_reg_289_pp0_iter3_reg[63:16] <= 48'b000000000000000000000000000000000000000000000000;
    zext_ln261_reg_289_pp0_iter4_reg[63:16] <= 48'b000000000000000000000000000000000000000000000000;
    zext_ln261_reg_289_pp0_iter5_reg[63:16] <= 48'b000000000000000000000000000000000000000000000000;
end

endmodule //hls_object_green_classification_hls_object_green_classification_Pipeline_PASS_3_5_2_in
