// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ContourApproximation_ContourApproximation_Pipeline_CHECK_DIFFER_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_address0,
        p_ce0,
        p_q0,
        p_address1,
        p_ce1,
        p_q1,
        sext_ln75,
        nb_pts_reduce_out,
        nb_pts_reduce_out_ap_vld,
        nb_pts_reduce_1_out,
        nb_pts_reduce_1_out_ap_vld,
        ap_return,
        grp_fu_21023_p_din0,
        grp_fu_21023_p_din1,
        grp_fu_21023_p_opcode,
        grp_fu_21023_p_dout0,
        grp_fu_21023_p_ce,
        grp_fu_42943_p_din0,
        grp_fu_42943_p_din1,
        grp_fu_42943_p_opcode,
        grp_fu_42943_p_dout0,
        grp_fu_42943_p_ce
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_state5 = 4'd4;
parameter    ap_ST_fsm_state6 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] p_address0;
output   p_ce0;
input  [63:0] p_q0;
output  [7:0] p_address1;
output   p_ce1;
input  [63:0] p_q1;
input  [16:0] sext_ln75;
output  [15:0] nb_pts_reduce_out;
output   nb_pts_reduce_out_ap_vld;
output  [15:0] nb_pts_reduce_1_out;
output   nb_pts_reduce_1_out_ap_vld;
output  [0:0] ap_return;
output  [31:0] grp_fu_21023_p_din0;
output  [31:0] grp_fu_21023_p_din1;
output  [4:0] grp_fu_21023_p_opcode;
input  [0:0] grp_fu_21023_p_dout0;
output   grp_fu_21023_p_ce;
output  [31:0] grp_fu_42943_p_din0;
output  [31:0] grp_fu_42943_p_din1;
output  [4:0] grp_fu_42943_p_opcode;
input  [0:0] grp_fu_42943_p_dout0;
output   grp_fu_42943_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_ce0;
reg p_ce1;
reg[15:0] nb_pts_reduce_out;
reg nb_pts_reduce_out_ap_vld;
reg nb_pts_reduce_1_out_ap_vld;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [31:0] sext_ln75_cast_fu_149_p1;
reg  signed [31:0] sext_ln75_cast_reg_441;
wire   [0:0] icmp_ln158_fu_166_p2;
reg   [0:0] icmp_ln158_reg_446;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln158_reg_446_pp0_iter1_reg;
wire   [0:0] icmp_ln163_fu_188_p2;
reg   [0:0] icmp_ln163_reg_460;
reg   [0:0] icmp_ln163_reg_460_pp0_iter1_reg;
wire   [31:0] bitcast_ln145_fu_202_p1;
wire   [31:0] bitcast_ln145_1_fu_211_p1;
wire   [0:0] icmp_ln145_fu_244_p2;
reg   [0:0] icmp_ln145_reg_474;
wire   [0:0] icmp_ln145_1_fu_250_p2;
reg   [0:0] icmp_ln145_1_reg_479;
wire   [0:0] icmp_ln145_2_fu_256_p2;
reg   [0:0] icmp_ln145_2_reg_484;
wire   [0:0] icmp_ln145_3_fu_262_p2;
reg   [0:0] icmp_ln145_3_reg_489;
wire   [31:0] bitcast_ln145_2_fu_278_p1;
wire   [31:0] bitcast_ln145_3_fu_293_p1;
wire   [0:0] icmp_ln145_4_fu_338_p2;
reg   [0:0] icmp_ln145_4_reg_504;
wire   [0:0] icmp_ln145_5_fu_344_p2;
reg   [0:0] icmp_ln145_5_reg_509;
wire   [0:0] icmp_ln145_6_fu_350_p2;
reg   [0:0] icmp_ln145_6_reg_514;
wire   [0:0] icmp_ln145_7_fu_356_p2;
reg   [0:0] icmp_ln145_7_reg_519;
reg   [15:0] nb_pts_reduce_load_reg_524;
reg    ap_enable_reg_pp0_iter2;
wire   [15:0] nb_pts_reduce_1_fu_414_p3;
reg   [15:0] nb_pts_reduce_1_reg_529;
wire    ap_block_pp0_stage0_subdone;
reg    ap_predicate_tran4to5_state2;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] ap_phi_mux_UnifiedRetVal_phi_fu_129_p4;
reg   [0:0] UnifiedRetVal_reg_125;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln158_fu_178_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln160_fu_183_p1;
reg   [15:0] nb_pts_reduce_fu_72;
reg   [31:0] i_fu_76;
wire   [31:0] add_ln160_fu_172_p2;
wire   [31:0] trunc_ln145_fu_198_p1;
wire   [31:0] trunc_ln145_4_fu_207_p1;
wire   [7:0] tmp_s_fu_216_p4;
wire   [22:0] trunc_ln145_5_fu_226_p1;
wire   [7:0] tmp_6_fu_230_p4;
wire   [22:0] trunc_ln145_6_fu_240_p1;
wire   [31:0] trunc_ln145_2_fu_268_p4;
wire   [31:0] trunc_ln145_3_fu_283_p4;
wire   [7:0] tmp_8_fu_298_p4;
wire   [22:0] trunc_ln145_9_fu_308_p4;
wire   [7:0] tmp_9_fu_318_p4;
wire   [22:0] trunc_ln145_s_fu_328_p4;
wire   [0:0] or_ln145_fu_362_p2;
wire   [0:0] or_ln145_1_fu_366_p2;
wire   [0:0] and_ln145_fu_370_p2;
wire   [0:0] or_ln145_2_fu_388_p2;
wire   [0:0] or_ln145_3_fu_392_p2;
wire   [0:0] and_ln145_2_fu_396_p2;
wire   [0:0] and_ln145_1_fu_376_p2;
wire   [0:0] and_ln145_3_fu_402_p2;
wire   [0:0] and_ln145_4_fu_408_p2;
wire   [15:0] add_ln161_fu_382_p2;
wire    ap_block_pp0_stage0_00001;
reg   [0:0] ap_return_preg;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg   [1:0] ap_exit_tran_regpp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_return_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_129_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln158_reg_446 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        UnifiedRetVal_reg_125 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        UnifiedRetVal_reg_125 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((icmp_ln158_fu_166_p2 == 1'd1)) begin
                        ap_exit_tran_regpp0[0] <= 1'b1;
        end else if ((ap_predicate_tran4to5_state2 == 1'b1)) begin
                        ap_exit_tran_regpp0[0] <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_76 <= 32'd0;
    end else if (((icmp_ln163_fu_188_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln158_fu_166_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_76 <= add_ln160_fu_172_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nb_pts_reduce_fu_72 <= 16'd0;
    end else if (((icmp_ln163_reg_460_pp0_iter1_reg == 1'd0) & (icmp_ln158_reg_446_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        nb_pts_reduce_fu_72 <= nb_pts_reduce_1_fu_414_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln158_reg_446 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln145_1_reg_479 <= icmp_ln145_1_fu_250_p2;
        icmp_ln145_2_reg_484 <= icmp_ln145_2_fu_256_p2;
        icmp_ln145_3_reg_489 <= icmp_ln145_3_fu_262_p2;
        icmp_ln145_4_reg_504 <= icmp_ln145_4_fu_338_p2;
        icmp_ln145_5_reg_509 <= icmp_ln145_5_fu_344_p2;
        icmp_ln145_6_reg_514 <= icmp_ln145_6_fu_350_p2;
        icmp_ln145_7_reg_519 <= icmp_ln145_7_fu_356_p2;
        icmp_ln145_reg_474 <= icmp_ln145_fu_244_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln158_reg_446 <= icmp_ln158_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln158_reg_446_pp0_iter1_reg <= icmp_ln158_reg_446;
        icmp_ln163_reg_460_pp0_iter1_reg <= icmp_ln163_reg_460;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln158_fu_166_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln163_reg_460 <= icmp_ln163_fu_188_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln158_reg_446_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        nb_pts_reduce_1_reg_529 <= nb_pts_reduce_1_fu_414_p3;
        nb_pts_reduce_load_reg_524 <= nb_pts_reduce_fu_72;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sext_ln75_cast_reg_441 <= sext_ln75_cast_fu_149_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((icmp_ln158_fu_166_p2 == 1'd1) | (ap_predicate_tran4to5_state2 == 1'b1)))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln158_reg_446 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_129_p4 = 1'd0;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_129_p4 = UnifiedRetVal_reg_125;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_129_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((icmp_ln158_reg_446 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        nb_pts_reduce_1_out_ap_vld = 1'b1;
    end else begin
        nb_pts_reduce_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        nb_pts_reduce_out = nb_pts_reduce_fu_72;
    end else if (((icmp_ln158_reg_446 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        nb_pts_reduce_out = nb_pts_reduce_load_reg_524;
    end else begin
        nb_pts_reduce_out = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((icmp_ln158_reg_446 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        nb_pts_reduce_out_ap_vld = 1'b1;
    end else begin
        nb_pts_reduce_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ce0 = 1'b1;
    end else begin
        p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ce1 = 1'b1;
    end else begin
        p_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_exit_tran_regpp0 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_exit_tran_regpp0 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_fu_172_p2 = (i_fu_76 + 32'd1);

assign add_ln161_fu_382_p2 = (nb_pts_reduce_fu_72 + 16'd1);

assign and_ln145_1_fu_376_p2 = (grp_fu_21023_p_dout0 & and_ln145_fu_370_p2);

assign and_ln145_2_fu_396_p2 = (or_ln145_3_fu_392_p2 & or_ln145_2_fu_388_p2);

assign and_ln145_3_fu_402_p2 = (grp_fu_42943_p_dout0 & and_ln145_2_fu_396_p2);

assign and_ln145_4_fu_408_p2 = (and_ln145_3_fu_402_p2 & and_ln145_1_fu_376_p2);

assign and_ln145_fu_370_p2 = (or_ln145_fu_362_p2 & or_ln145_1_fu_366_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_tran4to5_state2 = ((icmp_ln163_fu_188_p2 == 1'd1) & (icmp_ln158_fu_166_p2 == 1'd0));
end

assign bitcast_ln145_1_fu_211_p1 = trunc_ln145_4_fu_207_p1;

assign bitcast_ln145_2_fu_278_p1 = trunc_ln145_2_fu_268_p4;

assign bitcast_ln145_3_fu_293_p1 = trunc_ln145_3_fu_283_p4;

assign bitcast_ln145_fu_202_p1 = trunc_ln145_fu_198_p1;

assign grp_fu_21023_p_ce = 1'b1;

assign grp_fu_21023_p_din0 = bitcast_ln145_fu_202_p1;

assign grp_fu_21023_p_din1 = bitcast_ln145_1_fu_211_p1;

assign grp_fu_21023_p_opcode = 5'd1;

assign grp_fu_42943_p_ce = 1'b1;

assign grp_fu_42943_p_din0 = bitcast_ln145_2_fu_278_p1;

assign grp_fu_42943_p_din1 = bitcast_ln145_3_fu_293_p1;

assign grp_fu_42943_p_opcode = 5'd1;

assign icmp_ln145_1_fu_250_p2 = ((trunc_ln145_5_fu_226_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln145_2_fu_256_p2 = ((tmp_6_fu_230_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln145_3_fu_262_p2 = ((trunc_ln145_6_fu_240_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln145_4_fu_338_p2 = ((tmp_8_fu_298_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln145_5_fu_344_p2 = ((trunc_ln145_9_fu_308_p4 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln145_6_fu_350_p2 = ((tmp_9_fu_318_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln145_7_fu_356_p2 = ((trunc_ln145_s_fu_328_p4 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_244_p2 = ((tmp_s_fu_216_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln158_fu_166_p2 = ((i_fu_76 == 32'd250) ? 1'b1 : 1'b0);

assign icmp_ln163_fu_188_p2 = ((add_ln160_fu_172_p2 == sext_ln75_cast_reg_441) ? 1'b1 : 1'b0);

assign nb_pts_reduce_1_fu_414_p3 = ((and_ln145_4_fu_408_p2[0:0] == 1'b1) ? nb_pts_reduce_fu_72 : add_ln161_fu_382_p2);

assign nb_pts_reduce_1_out = nb_pts_reduce_1_reg_529;

assign or_ln145_1_fu_366_p2 = (icmp_ln145_3_reg_489 | icmp_ln145_2_reg_484);

assign or_ln145_2_fu_388_p2 = (icmp_ln145_5_reg_509 | icmp_ln145_4_reg_504);

assign or_ln145_3_fu_392_p2 = (icmp_ln145_7_reg_519 | icmp_ln145_6_reg_514);

assign or_ln145_fu_362_p2 = (icmp_ln145_reg_474 | icmp_ln145_1_reg_479);

assign p_address0 = zext_ln160_fu_183_p1;

assign p_address1 = zext_ln158_fu_178_p1;

assign sext_ln75_cast_fu_149_p1 = $signed(sext_ln75);

assign tmp_6_fu_230_p4 = {{p_q0[30:23]}};

assign tmp_8_fu_298_p4 = {{p_q1[62:55]}};

assign tmp_9_fu_318_p4 = {{p_q0[62:55]}};

assign tmp_s_fu_216_p4 = {{p_q1[30:23]}};

assign trunc_ln145_2_fu_268_p4 = {{p_q1[63:32]}};

assign trunc_ln145_3_fu_283_p4 = {{p_q0[63:32]}};

assign trunc_ln145_4_fu_207_p1 = p_q0[31:0];

assign trunc_ln145_5_fu_226_p1 = p_q1[22:0];

assign trunc_ln145_6_fu_240_p1 = p_q0[22:0];

assign trunc_ln145_9_fu_308_p4 = {{p_q1[54:32]}};

assign trunc_ln145_fu_198_p1 = p_q1[31:0];

assign trunc_ln145_s_fu_328_p4 = {{p_q0[54:32]}};

assign zext_ln158_fu_178_p1 = i_fu_76;

assign zext_ln160_fu_183_p1 = add_ln160_fu_172_p2;

always @ (posedge ap_clk) begin
    ap_exit_tran_regpp0[1] <= 1'b0;
end

endmodule //ContourApproximation_ContourApproximation_Pipeline_CHECK_DIFFER_LOOP
