-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ContourApproximation_LinearLine is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    FirstP_val : IN STD_LOGIC_VECTOR (63 downto 0);
    LastP_val : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of ContourApproximation_LinearLine is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (29 downto 0) := "000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (29 downto 0) := "000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (29 downto 0) := "000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (29 downto 0) := "000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (29 downto 0) := "000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (29 downto 0) := "000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (29 downto 0) := "000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (29 downto 0) := "000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (29 downto 0) := "000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (29 downto 0) := "001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (29 downto 0) := "010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (29 downto 0) := "100000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln9_fu_77_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln9_reg_386 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln9_fu_81_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln9_reg_391 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln9_1_fu_91_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln12_fu_125_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_reg_404 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_1_fu_131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_1_reg_409 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_2_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_2_reg_414 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_3_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_3_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_fu_149_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1_reg_424 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln18_fu_159_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln18_1_fu_175_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln18_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_reg_441 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_1_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_1_reg_446 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_2_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_2_reg_451 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_3_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_3_reg_456 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln12_1_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln12_1_reg_461 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal and_ln18_2_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_2_reg_468 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_52_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_475 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_56_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub2_reg_480 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_64_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inverse_reg_485 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal bitcast_ln26_1_fu_306_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_fu_60_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal L1_a_reg_495 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal mul_reg_501 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal L1_c_1_fu_316_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal L1_c_1_reg_506 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal grp_fu_52_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_52_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_60_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_60_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_69_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_69_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln9_1_fu_87_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_97_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln12_fu_107_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_1_fu_111_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln12_1_fu_121_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln18_1_fu_165_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_181_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln18_2_fu_191_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_4_fu_201_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln18_3_fu_211_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln12_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln12_1_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln12_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_69_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln18_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln18_1_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_73_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln12_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln26_fu_297_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln26_fu_300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln21_fu_311_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state30 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state30 : signal is "none";
    signal xor_ln15_fu_321_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal L1_c_fu_326_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal L1_c_3_fu_330_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln18_2_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln18_fu_350_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal L1_a_1_fu_361_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal L1_b_fu_343_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal L1_c_4_fu_337_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ContourApproximation_fsub_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ContourApproximation_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ContourApproximation_fdiv_32ns_32ns_32_12_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ContourApproximation_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    fsub_32ns_32ns_32_5_full_dsp_1_U1 : component ContourApproximation_fsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_52_p0,
        din1 => grp_fu_52_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_52_p2);

    fsub_32ns_32ns_32_5_full_dsp_1_U2 : component ContourApproximation_fsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => bitcast_ln18_fu_159_p1,
        din1 => bitcast_ln18_1_fu_175_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_56_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U3 : component ContourApproximation_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_60_p0,
        din1 => grp_fu_60_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_60_p2);

    fdiv_32ns_32ns_32_12_no_dsp_1_U4 : component ContourApproximation_fdiv_32ns_32ns_32_12_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_3F800000,
        din1 => sub_reg_475,
        ce => ap_const_logic_1,
        dout => grp_fu_64_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U5 : component ContourApproximation_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_69_p0,
        din1 => grp_fu_69_p1,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_1,
        dout => grp_fu_69_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U6 : component ContourApproximation_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => bitcast_ln18_fu_159_p1,
        din1 => bitcast_ln18_1_fu_175_p1,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_1,
        dout => grp_fu_73_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
                    ap_return_0_preg <= L1_a_1_fu_361_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg(23) <= '0';
                ap_return_1_preg(24) <= '0';
                ap_return_1_preg(25) <= '0';
                ap_return_1_preg(26) <= '0';
                ap_return_1_preg(27) <= '0';
                ap_return_1_preg(28) <= '0';
                ap_return_1_preg(29) <= '0';
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
                                        ap_return_1_preg(29 downto 23) <= L1_b_fu_343_p3(29 downto 23);
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
                    ap_return_2_preg <= L1_c_4_fu_337_p3;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                L1_a_reg_495 <= grp_fu_60_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state26)) then
                L1_c_1_reg_506 <= L1_c_1_fu_316_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                and_ln12_1_reg_461 <= and_ln12_1_fu_259_p2;
                and_ln18_2_reg_468 <= and_ln18_2_fu_291_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                bitcast_ln9_reg_391 <= bitcast_ln9_fu_81_p1;
                icmp_ln12_1_reg_409 <= icmp_ln12_1_fu_131_p2;
                icmp_ln12_2_reg_414 <= icmp_ln12_2_fu_137_p2;
                icmp_ln12_3_reg_419 <= icmp_ln12_3_fu_143_p2;
                icmp_ln12_reg_404 <= icmp_ln12_fu_125_p2;
                icmp_ln18_1_reg_446 <= icmp_ln18_1_fu_227_p2;
                icmp_ln18_2_reg_451 <= icmp_ln18_2_fu_233_p2;
                icmp_ln18_3_reg_456 <= icmp_ln18_3_fu_239_p2;
                icmp_ln18_reg_441 <= icmp_ln18_fu_221_p2;
                trunc_ln1_reg_424 <= FirstP_val(63 downto 32);
                trunc_ln9_reg_386 <= trunc_ln9_fu_77_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                inverse_reg_485 <= grp_fu_64_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state25) and (ap_const_lv1_0 = and_ln18_2_reg_468) and (ap_const_lv1_0 = and_ln12_1_reg_461))) then
                mul_reg_501 <= grp_fu_60_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                sub2_reg_480 <= grp_fu_56_p2;
                sub_reg_475 <= grp_fu_52_p2;
            end if;
        end if;
    end process;
    ap_return_1_preg(22 downto 0) <= "00000000000000000000000";
    ap_return_1_preg(31 downto 30) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    L1_a_1_fu_361_p3 <= 
        select_ln18_fu_350_p3 when (or_ln18_2_fu_357_p2(0) = '1') else 
        L1_a_reg_495;
    L1_b_fu_343_p3 <= 
        ap_const_lv32_0 when (and_ln12_1_reg_461(0) = '1') else 
        ap_const_lv32_3F800000;
    L1_c_1_fu_316_p1 <= xor_ln21_fu_311_p2;
    L1_c_3_fu_330_p3 <= 
        L1_c_fu_326_p1 when (and_ln12_1_reg_461(0) = '1') else 
        grp_fu_52_p2;
    L1_c_4_fu_337_p3 <= 
        L1_c_1_reg_506 when (and_ln18_2_reg_468(0) = '1') else 
        L1_c_3_fu_330_p3;
    L1_c_fu_326_p1 <= xor_ln15_fu_321_p2;
    and_ln12_1_fu_259_p2 <= (grp_fu_69_p2 and and_ln12_fu_253_p2);
    and_ln12_fu_253_p2 <= (or_ln12_fu_245_p2 and or_ln12_1_fu_249_p2);
    and_ln18_1_fu_279_p2 <= (grp_fu_73_p2 and and_ln18_fu_273_p2);
    and_ln18_2_fu_291_p2 <= (xor_ln12_fu_285_p2 and and_ln18_1_fu_279_p2);
    and_ln18_fu_273_p2 <= (or_ln18_fu_265_p2 and or_ln18_1_fu_269_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state30 <= ap_CS_fsm(29);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state30)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state30) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_CS_fsm_state30, L1_a_1_fu_361_p3, ap_return_0_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            ap_return_0 <= L1_a_1_fu_361_p3;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state30, L1_b_fu_343_p3, ap_return_1_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            ap_return_1 <= L1_b_fu_343_p3;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_CS_fsm_state30, L1_c_4_fu_337_p3, ap_return_2_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            ap_return_2 <= L1_c_4_fu_337_p3;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;

    bitcast_ln18_1_fu_175_p1 <= trunc_ln18_1_fu_165_p4;
    bitcast_ln18_fu_159_p1 <= trunc_ln1_fu_149_p4;
    bitcast_ln26_1_fu_306_p1 <= xor_ln26_fu_300_p2;
    bitcast_ln26_fu_297_p1 <= sub2_reg_480;
    bitcast_ln9_1_fu_91_p1 <= trunc_ln9_1_fu_87_p1;
    bitcast_ln9_fu_81_p1 <= trunc_ln9_fu_77_p1;

    grp_fu_52_p0_assign_proc : process(ap_CS_fsm_state1, bitcast_ln9_fu_81_p1, L1_c_1_fu_316_p1, ap_CS_fsm_state26)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            grp_fu_52_p0 <= L1_c_1_fu_316_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_52_p0 <= bitcast_ln9_fu_81_p1;
        else 
            grp_fu_52_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_52_p1_assign_proc : process(ap_CS_fsm_state1, bitcast_ln9_1_fu_91_p1, mul_reg_501, ap_CS_fsm_state26)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            grp_fu_52_p1 <= mul_reg_501;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_52_p1 <= bitcast_ln9_1_fu_91_p1;
        else 
            grp_fu_52_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_60_p0_assign_proc : process(inverse_reg_485, ap_CS_fsm_state18, L1_a_reg_495, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            grp_fu_60_p0 <= L1_a_reg_495;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_60_p0 <= inverse_reg_485;
        else 
            grp_fu_60_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_60_p1_assign_proc : process(bitcast_ln9_reg_391, bitcast_ln26_1_fu_306_p1, ap_CS_fsm_state18, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            grp_fu_60_p1 <= bitcast_ln9_reg_391;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_60_p1 <= bitcast_ln26_1_fu_306_p1;
        else 
            grp_fu_60_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_69_p0 <= trunc_ln9_fu_77_p1;
    grp_fu_69_p1 <= trunc_ln9_1_fu_87_p1;
    icmp_ln12_1_fu_131_p2 <= "1" when (trunc_ln12_fu_107_p1 = ap_const_lv23_0) else "0";
    icmp_ln12_2_fu_137_p2 <= "0" when (tmp_1_fu_111_p4 = ap_const_lv8_FF) else "1";
    icmp_ln12_3_fu_143_p2 <= "1" when (trunc_ln12_1_fu_121_p1 = ap_const_lv23_0) else "0";
    icmp_ln12_fu_125_p2 <= "0" when (tmp_fu_97_p4 = ap_const_lv8_FF) else "1";
    icmp_ln18_1_fu_227_p2 <= "1" when (trunc_ln18_2_fu_191_p4 = ap_const_lv23_0) else "0";
    icmp_ln18_2_fu_233_p2 <= "0" when (tmp_4_fu_201_p4 = ap_const_lv8_FF) else "1";
    icmp_ln18_3_fu_239_p2 <= "1" when (trunc_ln18_3_fu_211_p4 = ap_const_lv23_0) else "0";
    icmp_ln18_fu_221_p2 <= "0" when (tmp_3_fu_181_p4 = ap_const_lv8_FF) else "1";
    or_ln12_1_fu_249_p2 <= (icmp_ln12_3_reg_419 or icmp_ln12_2_reg_414);
    or_ln12_fu_245_p2 <= (icmp_ln12_reg_404 or icmp_ln12_1_reg_409);
    or_ln18_1_fu_269_p2 <= (icmp_ln18_3_reg_456 or icmp_ln18_2_reg_451);
    or_ln18_2_fu_357_p2 <= (and_ln18_2_reg_468 or and_ln12_1_reg_461);
    or_ln18_fu_265_p2 <= (icmp_ln18_reg_441 or icmp_ln18_1_reg_446);
    select_ln18_fu_350_p3 <= 
        ap_const_lv32_0 when (and_ln18_2_reg_468(0) = '1') else 
        ap_const_lv32_3F800000;
    tmp_1_fu_111_p4 <= LastP_val(30 downto 23);
    tmp_3_fu_181_p4 <= FirstP_val(62 downto 55);
    tmp_4_fu_201_p4 <= LastP_val(62 downto 55);
    tmp_fu_97_p4 <= FirstP_val(30 downto 23);
    trunc_ln12_1_fu_121_p1 <= LastP_val(23 - 1 downto 0);
    trunc_ln12_fu_107_p1 <= FirstP_val(23 - 1 downto 0);
    trunc_ln18_1_fu_165_p4 <= LastP_val(63 downto 32);
    trunc_ln18_2_fu_191_p4 <= FirstP_val(54 downto 32);
    trunc_ln18_3_fu_211_p4 <= LastP_val(54 downto 32);
    trunc_ln1_fu_149_p4 <= FirstP_val(63 downto 32);
    trunc_ln9_1_fu_87_p1 <= LastP_val(32 - 1 downto 0);
    trunc_ln9_fu_77_p1 <= FirstP_val(32 - 1 downto 0);
    xor_ln12_fu_285_p2 <= (ap_const_lv1_1 xor and_ln12_1_fu_259_p2);
    xor_ln15_fu_321_p2 <= (trunc_ln9_reg_386 xor ap_const_lv32_80000000);
    xor_ln21_fu_311_p2 <= (trunc_ln1_reg_424 xor ap_const_lv32_80000000);
    xor_ln26_fu_300_p2 <= (bitcast_ln26_fu_297_p1 xor ap_const_lv32_80000000);
end behav;
