-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity algo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    vecIn_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vecIn_0_ce0 : OUT STD_LOGIC;
    vecIn_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    vecIn_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vecIn_1_ce0 : OUT STD_LOGIC;
    vecIn_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    vecOut_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vecOut_0_ce0 : OUT STD_LOGIC;
    vecOut_0_we0 : OUT STD_LOGIC;
    vecOut_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vecOut_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vecOut_1_ce0 : OUT STD_LOGIC;
    vecOut_1_we0 : OUT STD_LOGIC;
    vecOut_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of algo is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "algo_algo,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.708000,HLS_SYN_LAT=331,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=633,HLS_SYN_LUT=777,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal a_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal a_ce0 : STD_LOGIC;
    signal a_we0 : STD_LOGIC;
    signal a_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal b_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal b_ce0 : STD_LOGIC;
    signal b_we0 : STD_LOGIC;
    signal b_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal c_ce0 : STD_LOGIC;
    signal c_we0 : STD_LOGIC;
    signal c_q0 : STD_LOGIC_VECTOR (2 downto 0);
    signal d_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal d_ce0 : STD_LOGIC;
    signal d_we0 : STD_LOGIC;
    signal d_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_done : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_idle : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_ready : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_0_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_1_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_we0 : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_d0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_we0 : STD_LOGIC;
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_d0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start : STD_LOGIC;
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_ap_done : STD_LOGIC;
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_ap_idle : STD_LOGIC;
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_ap_ready : STD_LOGIC;
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_a_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_a_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_c_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_c_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_c_we0 : STD_LOGIC;
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_c_d0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start : STD_LOGIC;
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_done : STD_LOGIC;
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_idle : STD_LOGIC;
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_ready : STD_LOGIC;
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_b_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_b_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_we0 : STD_LOGIC;
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_d0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_idle : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_ready : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_we0 : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_d_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_d_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_c_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_c_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_ce0 : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_we0 : STD_LOGIC;
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start_reg : STD_LOGIC := '0';
    signal grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component algo_algo_Pipeline_REMAINDER_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vecIn_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        vecIn_0_ce0 : OUT STD_LOGIC;
        vecIn_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        vecIn_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        vecIn_1_ce0 : OUT STD_LOGIC;
        vecIn_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        a_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        a_ce0 : OUT STD_LOGIC;
        a_we0 : OUT STD_LOGIC;
        a_d0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        b_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        b_ce0 : OUT STD_LOGIC;
        b_we0 : OUT STD_LOGIC;
        b_d0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component algo_algo_Pipeline_ADD_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        a_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        a_ce0 : OUT STD_LOGIC;
        a_q0 : IN STD_LOGIC_VECTOR (1 downto 0);
        c_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_we0 : OUT STD_LOGIC;
        c_d0 : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component algo_algo_Pipeline_MUL2ADD1_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        b_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        b_ce0 : OUT STD_LOGIC;
        b_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
        d_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        d_ce0 : OUT STD_LOGIC;
        d_we0 : OUT STD_LOGIC;
        d_d0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component algo_algo_Pipeline_DIVISION_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vecOut_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        vecOut_0_ce0 : OUT STD_LOGIC;
        vecOut_0_we0 : OUT STD_LOGIC;
        vecOut_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        d_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        d_ce0 : OUT STD_LOGIC;
        d_q0 : IN STD_LOGIC_VECTOR (4 downto 0);
        c_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
        vecOut_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        vecOut_1_ce0 : OUT STD_LOGIC;
        vecOut_1_we0 : OUT STD_LOGIC;
        vecOut_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component algo_a_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (1 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component algo_b_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (3 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component algo_c_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (2 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component algo_d_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (4 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    a_U : component algo_a_RAM_AUTO_1R1W
    generic map (
        DataWidth => 2,
        AddressRange => 100,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => a_address0,
        ce0 => a_ce0,
        we0 => a_we0,
        d0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_d0,
        q0 => a_q0);

    b_U : component algo_b_RAM_AUTO_1R1W
    generic map (
        DataWidth => 4,
        AddressRange => 100,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => b_address0,
        ce0 => b_ce0,
        we0 => b_we0,
        d0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_d0,
        q0 => b_q0);

    c_U : component algo_c_RAM_AUTO_1R1W
    generic map (
        DataWidth => 3,
        AddressRange => 100,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => c_address0,
        ce0 => c_ce0,
        we0 => c_we0,
        d0 => grp_algo_Pipeline_ADD_LOOP_fu_62_c_d0,
        q0 => c_q0);

    d_U : component algo_d_RAM_AUTO_1R1W
    generic map (
        DataWidth => 5,
        AddressRange => 100,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => d_address0,
        ce0 => d_ce0,
        we0 => d_we0,
        d0 => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_d0,
        q0 => d_q0);

    grp_algo_Pipeline_REMAINDER_LOOP_fu_50 : component algo_algo_Pipeline_REMAINDER_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start,
        ap_done => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_done,
        ap_idle => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_idle,
        ap_ready => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_ready,
        vecIn_0_address0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_0_address0,
        vecIn_0_ce0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_0_ce0,
        vecIn_0_q0 => vecIn_0_q0,
        vecIn_1_address0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_1_address0,
        vecIn_1_ce0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_1_ce0,
        vecIn_1_q0 => vecIn_1_q0,
        a_address0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_address0,
        a_ce0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_ce0,
        a_we0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_we0,
        a_d0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_d0,
        b_address0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_address0,
        b_ce0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_ce0,
        b_we0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_we0,
        b_d0 => grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_d0);

    grp_algo_Pipeline_ADD_LOOP_fu_62 : component algo_algo_Pipeline_ADD_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start,
        ap_done => grp_algo_Pipeline_ADD_LOOP_fu_62_ap_done,
        ap_idle => grp_algo_Pipeline_ADD_LOOP_fu_62_ap_idle,
        ap_ready => grp_algo_Pipeline_ADD_LOOP_fu_62_ap_ready,
        a_address0 => grp_algo_Pipeline_ADD_LOOP_fu_62_a_address0,
        a_ce0 => grp_algo_Pipeline_ADD_LOOP_fu_62_a_ce0,
        a_q0 => a_q0,
        c_address0 => grp_algo_Pipeline_ADD_LOOP_fu_62_c_address0,
        c_ce0 => grp_algo_Pipeline_ADD_LOOP_fu_62_c_ce0,
        c_we0 => grp_algo_Pipeline_ADD_LOOP_fu_62_c_we0,
        c_d0 => grp_algo_Pipeline_ADD_LOOP_fu_62_c_d0);

    grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68 : component algo_algo_Pipeline_MUL2ADD1_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start,
        ap_done => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_done,
        ap_idle => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_idle,
        ap_ready => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_ready,
        b_address0 => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_b_address0,
        b_ce0 => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_b_ce0,
        b_q0 => b_q0,
        d_address0 => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_address0,
        d_ce0 => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_ce0,
        d_we0 => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_we0,
        d_d0 => grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_d0);

    grp_algo_Pipeline_DIVISION_LOOP_fu_74 : component algo_algo_Pipeline_DIVISION_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start,
        ap_done => grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done,
        ap_idle => grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_idle,
        ap_ready => grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_ready,
        vecOut_0_address0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_address0,
        vecOut_0_ce0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_ce0,
        vecOut_0_we0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_we0,
        vecOut_0_d0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_d0,
        d_address0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_d_address0,
        d_ce0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_d_ce0,
        d_q0 => d_q0,
        c_address0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_c_address0,
        c_ce0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_c_ce0,
        c_q0 => c_q0,
        vecOut_1_address0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_address0,
        vecOut_1_ce0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_ce0,
        vecOut_1_we0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_we0,
        vecOut_1_d0 => grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_algo_Pipeline_ADD_LOOP_fu_62_ap_ready = ap_const_logic_1)) then 
                    grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_ready = ap_const_logic_1)) then 
                    grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_ready = ap_const_logic_1)) then 
                    grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_done, grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_block_state4_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    a_address0_assign_proc : process(grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_address0, grp_algo_Pipeline_ADD_LOOP_fu_62_a_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            a_address0 <= grp_algo_Pipeline_ADD_LOOP_fu_62_a_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            a_address0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_address0;
        else 
            a_address0 <= "XXXXXXX";
        end if; 
    end process;


    a_ce0_assign_proc : process(grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_ce0, grp_algo_Pipeline_ADD_LOOP_fu_62_a_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            a_ce0 <= grp_algo_Pipeline_ADD_LOOP_fu_62_a_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            a_ce0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_ce0;
        else 
            a_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    a_we0_assign_proc : process(grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            a_we0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_a_we0;
        else 
            a_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_done)
    begin
        if ((grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done)
    begin
        if ((grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(grp_algo_Pipeline_ADD_LOOP_fu_62_ap_done, grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_done = ap_const_logic_0) or (grp_algo_Pipeline_ADD_LOOP_fu_62_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    b_address0_assign_proc : process(grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_address0, grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_b_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            b_address0 <= grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_b_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            b_address0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_address0;
        else 
            b_address0 <= "XXXXXXX";
        end if; 
    end process;


    b_ce0_assign_proc : process(grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_ce0, grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_b_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            b_ce0 <= grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_b_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            b_ce0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_ce0;
        else 
            b_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    b_we0_assign_proc : process(grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            b_we0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_b_we0;
        else 
            b_we0 <= ap_const_logic_0;
        end if; 
    end process;


    c_address0_assign_proc : process(grp_algo_Pipeline_ADD_LOOP_fu_62_c_address0, grp_algo_Pipeline_DIVISION_LOOP_fu_74_c_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            c_address0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_c_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_address0 <= grp_algo_Pipeline_ADD_LOOP_fu_62_c_address0;
        else 
            c_address0 <= "XXXXXXX";
        end if; 
    end process;


    c_ce0_assign_proc : process(grp_algo_Pipeline_ADD_LOOP_fu_62_c_ce0, grp_algo_Pipeline_DIVISION_LOOP_fu_74_c_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            c_ce0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_c_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_ce0 <= grp_algo_Pipeline_ADD_LOOP_fu_62_c_ce0;
        else 
            c_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    c_we0_assign_proc : process(grp_algo_Pipeline_ADD_LOOP_fu_62_c_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_we0 <= grp_algo_Pipeline_ADD_LOOP_fu_62_c_we0;
        else 
            c_we0 <= ap_const_logic_0;
        end if; 
    end process;


    d_address0_assign_proc : process(grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_address0, grp_algo_Pipeline_DIVISION_LOOP_fu_74_d_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            d_address0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_d_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            d_address0 <= grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_address0;
        else 
            d_address0 <= "XXXXXXX";
        end if; 
    end process;


    d_ce0_assign_proc : process(grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_ce0, grp_algo_Pipeline_DIVISION_LOOP_fu_74_d_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            d_ce0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_d_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            d_ce0 <= grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_ce0;
        else 
            d_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    d_we0_assign_proc : process(grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            d_we0 <= grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_d_we0;
        else 
            d_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start <= grp_algo_Pipeline_ADD_LOOP_fu_62_ap_start_reg;
    grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_ap_start_reg;
    grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start <= grp_algo_Pipeline_MUL2ADD1_LOOP_fu_68_ap_start_reg;
    grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_ap_start_reg;
    vecIn_0_address0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_0_address0;
    vecIn_0_ce0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_0_ce0;
    vecIn_1_address0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_1_address0;
    vecIn_1_ce0 <= grp_algo_Pipeline_REMAINDER_LOOP_fu_50_vecIn_1_ce0;
    vecOut_0_address0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_address0;
    vecOut_0_ce0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_ce0;
    vecOut_0_d0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_d0;
    vecOut_0_we0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_0_we0;
    vecOut_1_address0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_address0;
    vecOut_1_ce0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_ce0;
    vecOut_1_d0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_d0;
    vecOut_1_we0 <= grp_algo_Pipeline_DIVISION_LOOP_fu_74_vecOut_1_we0;
end behav;
