-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity BackGrRemovalStream is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    input_stream_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    input_stream_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    input_stream_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    output_stream_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_stream_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TVALID : OUT STD_LOGIC;
    output_stream_TREADY : IN STD_LOGIC;
    input_stream_TVALID : IN STD_LOGIC;
    input_stream_TREADY : OUT STD_LOGIC );
end;


architecture behav of BackGrRemovalStream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "BackGrRemovalStream_BackGrRemovalStream,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.074000,HLS_SYN_LAT=76825,HLS_SYN_TPT=76826,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=4124,HLS_SYN_LUT=3805,HLS_VERSION=2023_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal threshold : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_start : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_done : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_continue : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_idle : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_ready : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_output_stream_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TVALID : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_output_stream_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_row_loop_proc1_U0_input_stream_TREADY : STD_LOGIC;

    component BackGrRemovalStream_Loop_row_loop_proc1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_stream_TVALID : IN STD_LOGIC;
        output_stream_TREADY : IN STD_LOGIC;
        output_stream_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        output_stream_TVALID : OUT STD_LOGIC;
        output_stream_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_stream_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        threshold : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        input_stream_TREADY : OUT STD_LOGIC;
        input_stream_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        input_stream_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component BackGrRemovalStream_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        threshold : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component BackGrRemovalStream_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        threshold => threshold,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    Loop_row_loop_proc1_U0 : component BackGrRemovalStream_Loop_row_loop_proc1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_row_loop_proc1_U0_ap_start,
        ap_done => Loop_row_loop_proc1_U0_ap_done,
        ap_continue => Loop_row_loop_proc1_U0_ap_continue,
        ap_idle => Loop_row_loop_proc1_U0_ap_idle,
        ap_ready => Loop_row_loop_proc1_U0_ap_ready,
        input_stream_TVALID => input_stream_TVALID,
        output_stream_TREADY => output_stream_TREADY,
        output_stream_TDATA => Loop_row_loop_proc1_U0_output_stream_TDATA,
        output_stream_TVALID => Loop_row_loop_proc1_U0_output_stream_TVALID,
        output_stream_TKEEP => Loop_row_loop_proc1_U0_output_stream_TKEEP,
        output_stream_TSTRB => Loop_row_loop_proc1_U0_output_stream_TSTRB,
        output_stream_TUSER => Loop_row_loop_proc1_U0_output_stream_TUSER,
        output_stream_TLAST => Loop_row_loop_proc1_U0_output_stream_TLAST,
        output_stream_TID => Loop_row_loop_proc1_U0_output_stream_TID,
        output_stream_TDEST => Loop_row_loop_proc1_U0_output_stream_TDEST,
        threshold => threshold,
        input_stream_TDATA => input_stream_TDATA,
        input_stream_TREADY => Loop_row_loop_proc1_U0_input_stream_TREADY,
        input_stream_TKEEP => input_stream_TKEEP,
        input_stream_TSTRB => input_stream_TSTRB,
        input_stream_TUSER => input_stream_TUSER,
        input_stream_TLAST => input_stream_TLAST,
        input_stream_TID => input_stream_TID,
        input_stream_TDEST => input_stream_TDEST);




    Loop_row_loop_proc1_U0_ap_continue <= ap_const_logic_1;
    Loop_row_loop_proc1_U0_ap_start <= ap_start;
    ap_done <= Loop_row_loop_proc1_U0_ap_done;
    ap_idle <= Loop_row_loop_proc1_U0_ap_idle;
    ap_ready <= Loop_row_loop_proc1_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    input_stream_TREADY <= Loop_row_loop_proc1_U0_input_stream_TREADY;
    output_stream_TDATA <= Loop_row_loop_proc1_U0_output_stream_TDATA;
    output_stream_TDEST <= Loop_row_loop_proc1_U0_output_stream_TDEST;
    output_stream_TID <= Loop_row_loop_proc1_U0_output_stream_TID;
    output_stream_TKEEP <= Loop_row_loop_proc1_U0_output_stream_TKEEP;
    output_stream_TLAST <= Loop_row_loop_proc1_U0_output_stream_TLAST;
    output_stream_TSTRB <= Loop_row_loop_proc1_U0_output_stream_TSTRB;
    output_stream_TUSER <= Loop_row_loop_proc1_U0_output_stream_TUSER;
    output_stream_TVALID <= Loop_row_loop_proc1_U0_output_stream_TVALID;
end behav;
