-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity BackGrRemovalStream is
port (
    input_stream_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    input_stream_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    input_stream_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    output_stream_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_stream_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    output_stream_TVALID : OUT STD_LOGIC;
    output_stream_TREADY : IN STD_LOGIC;
    input_stream_TVALID : IN STD_LOGIC;
    input_stream_TREADY : OUT STD_LOGIC );
end;


architecture behav of BackGrRemovalStream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "BackGrRemovalStream_BackGrRemovalStream,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.074000,HLS_SYN_LAT=76825,HLS_SYN_TPT=76826,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=3674,HLS_SYN_LUT=3433,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_start : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_done : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_continue : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_idle : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_ap_ready : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_output_stream_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TVALID : STD_LOGIC;
    signal Loop_row_loop_proc1_U0_output_stream_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_row_loop_proc1_U0_output_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal Loop_row_loop_proc1_U0_input_stream_TREADY : STD_LOGIC;

    component BackGrRemovalStream_Loop_row_loop_proc1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_stream_TVALID : IN STD_LOGIC;
        output_stream_TREADY : IN STD_LOGIC;
        output_stream_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        output_stream_TVALID : OUT STD_LOGIC;
        output_stream_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_stream_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        input_stream_TREADY : OUT STD_LOGIC;
        input_stream_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        input_stream_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    Loop_row_loop_proc1_U0 : component BackGrRemovalStream_Loop_row_loop_proc1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_row_loop_proc1_U0_ap_start,
        ap_done => Loop_row_loop_proc1_U0_ap_done,
        ap_continue => Loop_row_loop_proc1_U0_ap_continue,
        ap_idle => Loop_row_loop_proc1_U0_ap_idle,
        ap_ready => Loop_row_loop_proc1_U0_ap_ready,
        input_stream_TVALID => input_stream_TVALID,
        output_stream_TREADY => output_stream_TREADY,
        output_stream_TDATA => Loop_row_loop_proc1_U0_output_stream_TDATA,
        output_stream_TVALID => Loop_row_loop_proc1_U0_output_stream_TVALID,
        output_stream_TKEEP => Loop_row_loop_proc1_U0_output_stream_TKEEP,
        output_stream_TSTRB => Loop_row_loop_proc1_U0_output_stream_TSTRB,
        output_stream_TUSER => Loop_row_loop_proc1_U0_output_stream_TUSER,
        output_stream_TLAST => Loop_row_loop_proc1_U0_output_stream_TLAST,
        output_stream_TID => Loop_row_loop_proc1_U0_output_stream_TID,
        output_stream_TDEST => Loop_row_loop_proc1_U0_output_stream_TDEST,
        input_stream_TDATA => input_stream_TDATA,
        input_stream_TREADY => Loop_row_loop_proc1_U0_input_stream_TREADY,
        input_stream_TKEEP => input_stream_TKEEP,
        input_stream_TSTRB => input_stream_TSTRB,
        input_stream_TUSER => input_stream_TUSER,
        input_stream_TLAST => input_stream_TLAST,
        input_stream_TID => input_stream_TID,
        input_stream_TDEST => input_stream_TDEST);




    Loop_row_loop_proc1_U0_ap_continue <= ap_const_logic_1;
    Loop_row_loop_proc1_U0_ap_start <= ap_const_logic_1;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    input_stream_TREADY <= Loop_row_loop_proc1_U0_input_stream_TREADY;
    output_stream_TDATA <= Loop_row_loop_proc1_U0_output_stream_TDATA;
    output_stream_TDEST <= Loop_row_loop_proc1_U0_output_stream_TDEST;
    output_stream_TID <= Loop_row_loop_proc1_U0_output_stream_TID;
    output_stream_TKEEP <= Loop_row_loop_proc1_U0_output_stream_TKEEP;
    output_stream_TLAST <= Loop_row_loop_proc1_U0_output_stream_TLAST;
    output_stream_TSTRB <= Loop_row_loop_proc1_U0_output_stream_TSTRB;
    output_stream_TUSER <= Loop_row_loop_proc1_U0_output_stream_TUSER;
    output_stream_TVALID <= Loop_row_loop_proc1_U0_output_stream_TVALID;
end behav;
