-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_object_green_classification_hls_object_green_classification_Pipeline_pass_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    next_label_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    obj_x_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    obj_x_ce0 : OUT STD_LOGIC;
    obj_x_we0 : OUT STD_LOGIC;
    obj_x_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    obj_y_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    obj_y_ce0 : OUT STD_LOGIC;
    obj_y_we0 : OUT STD_LOGIC;
    obj_y_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    obj_is_green_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    obj_is_green_ce0 : OUT STD_LOGIC;
    obj_is_green_we0 : OUT STD_LOGIC;
    obj_is_green_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    count_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    count_out_ap_vld : OUT STD_LOGIC;
    parent_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    parent_ce0 : OUT STD_LOGIC;
    parent_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    is_external_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    is_external_ce0 : OUT STD_LOGIC;
    is_external_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    min_x_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_x_ce0 : OUT STD_LOGIC;
    min_x_q0 : IN STD_LOGIC_VECTOR (8 downto 0);
    max_x_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_x_ce0 : OUT STD_LOGIC;
    max_x_q0 : IN STD_LOGIC_VECTOR (8 downto 0);
    min_y_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_y_ce0 : OUT STD_LOGIC;
    min_y_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    max_y_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_y_ce0 : OUT STD_LOGIC;
    max_y_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    imgR_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    imgR_ce0 : OUT STD_LOGIC;
    imgR_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    imgG_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    imgG_ce0 : OUT STD_LOGIC;
    imgG_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    imgB_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    imgB_ce0 : OUT STD_LOGIC;
    imgB_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    center_is_green_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    center_is_green_ce1 : OUT STD_LOGIC;
    center_is_green_we1 : OUT STD_LOGIC;
    center_is_green_d1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of hls_object_green_classification_hls_object_green_classification_Pipeline_pass_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv10_360 : STD_LOGIC_VECTOR (9 downto 0) := "1101100000";
    constant ap_const_lv9_78 : STD_LOGIC_VECTOR (8 downto 0) := "001111000";
    constant ap_const_lv8_50 : STD_LOGIC_VECTOR (7 downto 0) := "01010000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal and_ln276_reg_552 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_1_reg_539 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal count_1_reg_545 : STD_LOGIC_VECTOR (15 downto 0);
    signal count_1_reg_545_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln276_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln276_reg_552_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln278_fu_340_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln278_reg_556 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln278_reg_556_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln278_reg_556_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln278_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln278_reg_571 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln278_reg_571_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln278_reg_571_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal is_external_load_reg_580 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_external_load_reg_580_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln_reg_604 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln1_reg_610 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln282_fu_479_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln282_reg_632 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln17_1_fu_519_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln17_1_reg_637 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln281_3_fu_461_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_102 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_2_fu_350_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal count_fu_106 : STD_LOGIC_VECTOR (15 downto 0);
    signal count_2_fu_360_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_count_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_318_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln276_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln276_1_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln279_1_fu_374_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln279_fu_370_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln279_fu_378_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln280_1_fu_398_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln280_fu_394_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln280_fu_402_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_s_fu_424_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_435_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln281_fu_431_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln281_1_fu_442_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln281_fu_446_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln281_2_fu_452_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln281_1_fu_455_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln279_2_fu_418_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln282_fu_468_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln280_2_fu_421_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln283_fu_484_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln17_1_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_2_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln17_fu_513_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to3 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_487 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component hls_object_green_classification_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component hls_object_green_classification_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    count_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    count_fu_106 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_condition_487)) then 
                    count_fu_106 <= count_2_fu_360_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_fu_102 <= ap_const_lv16_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln276_reg_552))) then 
                i_fu_102 <= i_2_fu_350_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (is_external_load_reg_580_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln278_reg_571_pp0_iter1_reg = ap_const_lv1_1))) then
                and_ln17_1_reg_637 <= and_ln17_1_fu_519_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln276_reg_552 <= and_ln276_fu_334_p2;
                and_ln276_reg_552_pp0_iter1_reg <= and_ln276_reg_552;
                count_1_reg_545_pp0_iter1_reg <= count_1_reg_545;
                i_1_reg_539 <= ap_sig_allocacmp_i_1;
                is_external_load_reg_580_pp0_iter2_reg <= is_external_load_reg_580;
                    zext_ln278_reg_556_pp0_iter1_reg(15 downto 0) <= zext_ln278_reg_556(15 downto 0);
                    zext_ln278_reg_556_pp0_iter2_reg(15 downto 0) <= zext_ln278_reg_556_pp0_iter1_reg(15 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                count_1_reg_545 <= ap_sig_allocacmp_count_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln276_reg_552))) then
                icmp_ln278_reg_571 <= icmp_ln278_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln278_reg_571_pp0_iter1_reg <= icmp_ln278_reg_571;
                icmp_ln278_reg_571_pp0_iter2_reg <= icmp_ln278_reg_571_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln278_reg_571 = ap_const_lv1_1))) then
                is_external_load_reg_580 <= is_external_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (is_external_load_reg_580 = ap_const_lv1_1) and (icmp_ln278_reg_571 = ap_const_lv1_1))) then
                lshr_ln1_reg_610 <= add_ln280_fu_402_p2(8 downto 1);
                lshr_ln_reg_604 <= add_ln279_fu_378_p2(9 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_lv1_1 = and_ln276_fu_334_p2))) then
                    zext_ln278_reg_556(15 downto 0) <= zext_ln278_fu_340_p1(15 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (is_external_load_reg_580 = ap_const_lv1_1) and (icmp_ln278_reg_571_pp0_iter1_reg = ap_const_lv1_1))) then
                    zext_ln282_reg_632(15 downto 0) <= zext_ln282_fu_479_p1(15 downto 0);
            end if;
        end if;
    end process;
    zext_ln278_reg_556(63 downto 16) <= "000000000000000000000000000000000000000000000000";
    zext_ln278_reg_556_pp0_iter1_reg(63 downto 16) <= "000000000000000000000000000000000000000000000000";
    zext_ln278_reg_556_pp0_iter2_reg(63 downto 16) <= "000000000000000000000000000000000000000000000000";
    zext_ln282_reg_632(63 downto 16) <= "000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter2_stage0, ap_idle_pp0_0to1, ap_idle_pp0_1to3, ap_done_pending_pp0, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to3 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln279_fu_378_p2 <= std_logic_vector(unsigned(zext_ln279_1_fu_374_p1) + unsigned(zext_ln279_fu_370_p1));
    add_ln280_fu_402_p2 <= std_logic_vector(unsigned(zext_ln280_1_fu_398_p1) + unsigned(zext_ln280_fu_394_p1));
    add_ln281_1_fu_455_p2 <= std_logic_vector(unsigned(add_ln281_fu_446_p2) + unsigned(zext_ln281_2_fu_452_p1));
    add_ln281_fu_446_p2 <= std_logic_vector(unsigned(zext_ln281_fu_431_p1) + unsigned(zext_ln281_1_fu_442_p1));
    add_ln282_fu_468_p2 <= std_logic_vector(unsigned(zext_ln279_2_fu_418_p1) + unsigned(ap_const_lv10_360));
    and_ln17_1_fu_519_p2 <= (icmp_ln17_fu_495_p2 and and_ln17_fu_513_p2);
    and_ln17_fu_513_p2 <= (icmp_ln17_2_fu_507_p2 and icmp_ln17_1_fu_501_p2);
    and_ln276_fu_334_p2 <= (icmp_ln276_fu_312_p2 and icmp_ln276_1_fu_328_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_487_assign_proc : process(ap_enable_reg_pp0_iter1, is_external_q0, icmp_ln278_reg_571)
    begin
                ap_condition_487 <= ((is_external_q0 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln278_reg_571 = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, and_ln276_reg_552)
    begin
        if (((ap_const_lv1_0 = and_ln276_reg_552) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, and_ln276_reg_552_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_lv1_0 = and_ln276_reg_552_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (not(((ap_loop_exit_ready = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_count_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, count_fu_106, count_2_fu_360_p2, ap_condition_487)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_count_1 <= ap_const_lv16_0;
            elsif ((ap_const_boolean_1 = ap_condition_487)) then 
                ap_sig_allocacmp_count_1 <= count_2_fu_360_p2;
            else 
                ap_sig_allocacmp_count_1 <= count_fu_106;
            end if;
        else 
            ap_sig_allocacmp_count_1 <= count_fu_106;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_102, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv16_1;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_102;
        end if; 
    end process;

    center_is_green_address1 <= zext_ln278_reg_556_pp0_iter2_reg(9 - 1 downto 0);

    center_is_green_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            center_is_green_ce1 <= ap_const_logic_1;
        else 
            center_is_green_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    center_is_green_d1 <= and_ln17_1_reg_637;

    center_is_green_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, icmp_ln278_reg_571_pp0_iter2_reg, is_external_load_reg_580_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (is_external_load_reg_580_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln278_reg_571_pp0_iter2_reg = ap_const_lv1_1))) then 
            center_is_green_we1 <= ap_const_logic_1;
        else 
            center_is_green_we1 <= ap_const_logic_0;
        end if; 
    end process;

    count_2_fu_360_p2 <= std_logic_vector(unsigned(count_1_reg_545) + unsigned(ap_const_lv16_1));
    count_out <= count_1_reg_545_pp0_iter1_reg;

    count_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, and_ln276_reg_552_pp0_iter1_reg)
    begin
        if (((ap_const_lv1_0 = and_ln276_reg_552_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            count_out_ap_vld <= ap_const_logic_1;
        else 
            count_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_350_p2 <= std_logic_vector(unsigned(i_1_reg_539) + unsigned(ap_const_lv16_1));
    icmp_ln17_1_fu_501_p2 <= "1" when (unsigned(imgG_q0) > unsigned(imgB_q0)) else "0";
    icmp_ln17_2_fu_507_p2 <= "1" when (unsigned(imgG_q0) > unsigned(ap_const_lv8_50)) else "0";
    icmp_ln17_fu_495_p2 <= "1" when (unsigned(imgG_q0) > unsigned(imgR_q0)) else "0";
    icmp_ln276_1_fu_328_p2 <= "1" when (tmp_fu_318_p4 = ap_const_lv11_0) else "0";
    icmp_ln276_fu_312_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) < unsigned(next_label_5)) else "0";
    icmp_ln278_fu_345_p2 <= "1" when (parent_q0 = i_1_reg_539) else "0";
    imgB_address0 <= zext_ln281_3_fu_461_p1(17 - 1 downto 0);

    imgB_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imgB_ce0 <= ap_const_logic_1;
        else 
            imgB_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    imgG_address0 <= zext_ln281_3_fu_461_p1(17 - 1 downto 0);

    imgG_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imgG_ce0 <= ap_const_logic_1;
        else 
            imgG_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    imgR_address0 <= zext_ln281_3_fu_461_p1(17 - 1 downto 0);

    imgR_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imgR_ce0 <= ap_const_logic_1;
        else 
            imgR_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    is_external_address0 <= zext_ln278_reg_556(9 - 1 downto 0);

    is_external_ce0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            is_external_ce0 <= ap_const_logic_1;
        else 
            is_external_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    max_x_address0 <= zext_ln278_reg_556(9 - 1 downto 0);

    max_x_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            max_x_ce0 <= ap_const_logic_1;
        else 
            max_x_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    max_y_address0 <= zext_ln278_reg_556(9 - 1 downto 0);

    max_y_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            max_y_ce0 <= ap_const_logic_1;
        else 
            max_y_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    min_x_address0 <= zext_ln278_reg_556(9 - 1 downto 0);

    min_x_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            min_x_ce0 <= ap_const_logic_1;
        else 
            min_x_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    min_y_address0 <= zext_ln278_reg_556(9 - 1 downto 0);

    min_y_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            min_y_ce0 <= ap_const_logic_1;
        else 
            min_y_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    obj_is_green_address0 <= zext_ln282_reg_632(5 - 1 downto 0);

    obj_is_green_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            obj_is_green_ce0 <= ap_const_logic_1;
        else 
            obj_is_green_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    obj_is_green_d0 <= and_ln17_1_reg_637;

    obj_is_green_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, icmp_ln278_reg_571_pp0_iter2_reg, is_external_load_reg_580_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (is_external_load_reg_580_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln278_reg_571_pp0_iter2_reg = ap_const_lv1_1))) then 
            obj_is_green_we0 <= ap_const_logic_1;
        else 
            obj_is_green_we0 <= ap_const_logic_0;
        end if; 
    end process;

    obj_x_address0 <= zext_ln282_fu_479_p1(5 - 1 downto 0);

    obj_x_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            obj_x_ce0 <= ap_const_logic_1;
        else 
            obj_x_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        obj_x_d0 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln282_fu_468_p2),16));


    obj_x_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln278_reg_571_pp0_iter1_reg, is_external_load_reg_580)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (is_external_load_reg_580 = ap_const_lv1_1) and (icmp_ln278_reg_571_pp0_iter1_reg = ap_const_lv1_1))) then 
            obj_x_we0 <= ap_const_logic_1;
        else 
            obj_x_we0 <= ap_const_logic_0;
        end if; 
    end process;

    obj_y_address0 <= zext_ln282_fu_479_p1(5 - 1 downto 0);

    obj_y_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            obj_y_ce0 <= ap_const_logic_1;
        else 
            obj_y_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        obj_y_d0 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln283_fu_484_p2),16));


    obj_y_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln278_reg_571_pp0_iter1_reg, is_external_load_reg_580)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (is_external_load_reg_580 = ap_const_lv1_1) and (icmp_ln278_reg_571_pp0_iter1_reg = ap_const_lv1_1))) then 
            obj_y_we0 <= ap_const_logic_1;
        else 
            obj_y_we0 <= ap_const_logic_0;
        end if; 
    end process;

    parent_address0 <= zext_ln278_fu_340_p1(9 - 1 downto 0);

    parent_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            parent_ce0 <= ap_const_logic_1;
        else 
            parent_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln283_fu_484_p2 <= std_logic_vector(unsigned(ap_const_lv9_78) - unsigned(zext_ln280_2_fu_421_p1));
    tmp_1_fu_435_p3 <= (lshr_ln1_reg_610 & ap_const_lv6_0);
    tmp_fu_318_p4 <= ap_sig_allocacmp_count_1(15 downto 5);
    tmp_s_fu_424_p3 <= (lshr_ln1_reg_610 & ap_const_lv8_0);
    zext_ln278_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
    zext_ln279_1_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(max_x_q0),10));
    zext_ln279_2_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_reg_604),10));
    zext_ln279_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(min_x_q0),10));
    zext_ln280_1_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(max_y_q0),9));
    zext_ln280_2_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_reg_610),9));
    zext_ln280_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(min_y_q0),9));
    zext_ln281_1_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_435_p3),17));
    zext_ln281_2_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_reg_604),17));
    zext_ln281_3_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln281_1_fu_455_p2),64));
    zext_ln281_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_424_p3),17));
    zext_ln282_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(count_1_reg_545_pp0_iter1_reg),64));
end behav;
