

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788"},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.BackGrRemoval_stream_v2_stream_stream_axis_0_ap_uint_8_int_int_linebuf_7_U"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.BackGrRemoval_stream_v2_stream_stream_axis_0_ap_uint_8_int_int_linebuf_6_U"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.BackGrRemoval_stream_v2_stream_stream_axis_0_ap_uint_8_int_int_linebuf_5_U"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.BackGrRemoval_stream_v2_stream_stream_axis_0_ap_uint_8_int_int_linebuf_4_U"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.BackGrRemoval_stream_v2_stream_stream_axis_0_ap_uint_8_int_int_linebuf_3_U"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.BackGrRemoval_stream_v2_stream_stream_axis_0_ap_uint_8_int_int_linebuf_2_U"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.BackGrRemoval_stream_v2_stream_stream_axis_0_ap_uint_8_int_int_linebuf_1_U"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.BackGrRemoval_stream_v2_stream_stream_axis_0_ap_uint_8_int_int_linebuf_U"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.sdiv_16ns_9ns_16_20_1_U1"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.sdiv_16ns_9ns_16_20_1_U2"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_BackGrRemoval_stream_v2_Pipeline_VITIS_LOOP_84_1_fu_788.sdiv_16ns_9ns_16_20_1_U3"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U246"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_data_V_U"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_keep_V_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_strb_V_U"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_user_V_U"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_last_V_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_id_V_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_dest_V_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_data_V_U"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_keep_V_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_strb_V_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_user_V_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_last_V_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_id_V_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_dest_V_U"}]}
set DependenceCheckSize 0
