// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_rgb_green_outline_fixed_sobel_rgb_green_outline_fixed,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.080000,HLS_SYN_LAT=153614,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1158,HLS_SYN_LUT=1233,HLS_VERSION=2023_1}" *)

module sobel_rgb_green_outline_fixed (
        ap_clk,
        ap_rst_n,
        in_stream_TVALID,
        out_stream_TREADY,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst_n;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [23:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [2:0] in_stream_TKEEP;
input  [2:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [23:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [2:0] out_stream_TKEEP;
output  [2:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln35_reg_875;
reg    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_state12_pp0_stage1_iter5;
reg    ap_block_state14_pp0_stage1_iter6;
reg    ap_enable_reg_pp0_iter6;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
wire    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
reg    ap_ready_int;
wire   [8:0] sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_address0;
reg    sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_ce0;
reg    sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_we0;
wire   [8:0] sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_address1;
reg    sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_ce1;
wire   [7:0] sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_q1;
wire   [8:0] sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_address0;
reg    sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_ce0;
reg    sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_we0;
wire   [8:0] sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_address1;
reg    sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_ce1;
wire   [7:0] sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_q1;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage1;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter7;
wire    ap_block_pp0_stage0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
reg    ap_block_state13_pp0_stage0_iter6;
reg    ap_block_state15_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln35_fu_272_p2;
reg   [0:0] icmp_ln35_reg_875_pp0_iter1_reg;
reg   [0:0] icmp_ln35_reg_875_pp0_iter2_reg;
reg   [0:0] icmp_ln35_reg_875_pp0_iter3_reg;
reg   [0:0] icmp_ln35_reg_875_pp0_iter4_reg;
reg   [0:0] icmp_ln35_reg_875_pp0_iter5_reg;
reg   [2:0] in_pix_keep_V_reg_879;
reg    ap_block_pp0_stage1_11001;
reg   [2:0] in_pix_keep_V_reg_879_pp0_iter1_reg;
reg   [2:0] in_pix_keep_V_reg_879_pp0_iter2_reg;
reg   [2:0] in_pix_keep_V_reg_879_pp0_iter3_reg;
reg   [2:0] in_pix_keep_V_reg_879_pp0_iter4_reg;
reg   [2:0] in_pix_keep_V_reg_879_pp0_iter5_reg;
reg   [2:0] in_pix_strb_V_reg_884;
reg   [2:0] in_pix_strb_V_reg_884_pp0_iter1_reg;
reg   [2:0] in_pix_strb_V_reg_884_pp0_iter2_reg;
reg   [2:0] in_pix_strb_V_reg_884_pp0_iter3_reg;
reg   [2:0] in_pix_strb_V_reg_884_pp0_iter4_reg;
reg   [2:0] in_pix_strb_V_reg_884_pp0_iter5_reg;
reg   [0:0] in_pix_user_V_reg_889;
reg   [0:0] in_pix_user_V_reg_889_pp0_iter1_reg;
reg   [0:0] in_pix_user_V_reg_889_pp0_iter2_reg;
reg   [0:0] in_pix_user_V_reg_889_pp0_iter3_reg;
reg   [0:0] in_pix_user_V_reg_889_pp0_iter4_reg;
reg   [0:0] in_pix_user_V_reg_889_pp0_iter5_reg;
reg   [0:0] in_pix_last_V_reg_894;
reg   [0:0] in_pix_last_V_reg_894_pp0_iter1_reg;
reg   [0:0] in_pix_last_V_reg_894_pp0_iter2_reg;
reg   [0:0] in_pix_last_V_reg_894_pp0_iter3_reg;
reg   [0:0] in_pix_last_V_reg_894_pp0_iter4_reg;
reg   [0:0] in_pix_last_V_reg_894_pp0_iter5_reg;
wire   [7:0] B_fu_309_p4;
reg   [7:0] B_reg_899;
reg   [7:0] B_reg_899_pp0_iter1_reg;
reg   [7:0] B_reg_899_pp0_iter2_reg;
reg   [7:0] B_reg_899_pp0_iter3_reg;
reg   [7:0] B_reg_899_pp0_iter4_reg;
reg   [7:0] B_reg_899_pp0_iter5_reg;
reg   [7:0] G_reg_905;
reg   [7:0] G_reg_905_pp0_iter1_reg;
reg   [7:0] G_reg_905_pp0_iter2_reg;
reg   [7:0] G_reg_905_pp0_iter3_reg;
reg   [7:0] G_reg_905_pp0_iter4_reg;
reg   [7:0] G_reg_905_pp0_iter5_reg;
wire   [7:0] R_fu_329_p1;
reg   [7:0] R_reg_912;
reg   [7:0] R_reg_912_pp0_iter1_reg;
reg   [7:0] R_reg_912_pp0_iter2_reg;
reg   [7:0] R_reg_912_pp0_iter3_reg;
reg   [7:0] R_reg_912_pp0_iter4_reg;
reg   [7:0] R_reg_912_pp0_iter5_reg;
(* use_dsp48 = "no" *) wire   [40:0] add_ln46_1_fu_386_p2;
reg   [40:0] add_ln46_1_reg_930;
reg   [8:0] sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_addr_reg_940;
reg   [8:0] sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_addr_reg_946;
wire   [0:0] icmp_ln73_fu_417_p2;
reg   [0:0] icmp_ln73_reg_952;
wire   [31:0] col_1_fu_423_p2;
reg   [31:0] col_1_reg_957;
wire   [0:0] trunc_ln35_fu_438_p1;
reg   [0:0] trunc_ln35_reg_963;
reg   [7:0] gray_reg_967;
wire   [7:0] top_3_fu_478_p3;
reg   [7:0] top_3_reg_975;
wire   [7:0] middle_3_fu_502_p3;
reg   [7:0] middle_3_reg_982;
wire   [0:0] and_ln73_fu_516_p2;
reg   [0:0] and_ln73_reg_987;
reg   [0:0] and_ln73_reg_987_pp0_iter4_reg;
reg   [0:0] and_ln73_reg_987_pp0_iter5_reg;
wire   [9:0] add_ln76_fu_537_p2;
reg   [9:0] add_ln76_reg_994;
wire   [9:0] add_ln79_fu_555_p2;
reg   [9:0] add_ln79_reg_999;
wire   [10:0] gx_fu_672_p2;
reg   [10:0] gx_reg_1004;
wire   [10:0] gy_fu_718_p2;
reg   [10:0] gy_reg_1009;
wire   [20:0] mul_ln81_fu_736_p2;
reg  signed [20:0] mul_ln81_reg_1014;
wire  signed [20:0] sext_ln81_1_fu_742_p1;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter4_stage0;
reg    ap_enable_reg_pp0_iter5;
wire   [63:0] zext_ln65_fu_398_p1;
reg   [16:0] i_fu_134;
wire   [16:0] i_2_fu_278_p2;
wire    ap_loop_init;
reg   [16:0] ap_sig_allocacmp_i_1;
reg   [31:0] col_fu_138;
wire   [31:0] col_2_fu_572_p3;
reg   [31:0] row_fu_142;
wire   [31:0] row_3_fu_579_p3;
reg   [7:0] p_0_0_010211419_fu_146;
reg   [7:0] p_0_0_01021_11421_fu_150;
reg   [7:0] p_0_0_01021_21423_fu_154;
reg   [7:0] top_2_fu_158;
reg   [7:0] middle_2_fu_162;
reg   [7:0] gray_1_fu_166;
reg    ap_block_pp0_stage1_01001;
wire   [40:0] grp_fu_249_p0;
wire   [42:0] grp_fu_249_p1;
wire   [7:0] mul_ln46_fu_340_p0;
wire   [6:0] mul_ln46_fu_340_p1;
wire   [13:0] mul_ln46_fu_340_p2;
wire   [12:0] shl_ln_fu_350_p3;
wire   [8:0] shl_ln46_1_fu_361_p3;
wire   [13:0] zext_ln46_fu_357_p1;
wire   [13:0] zext_ln46_1_fu_368_p1;
wire   [13:0] sub_ln46_fu_372_p2;
wire  signed [39:0] sext_ln46_fu_378_p1;
wire   [40:0] grp_fu_800_p3;
wire   [40:0] zext_ln46_4_fu_382_p1;
wire   [30:0] tmp_1_fu_407_p4;
wire   [55:0] grp_fu_249_p2;
wire   [30:0] tmp_fu_452_p4;
wire   [0:0] icmp_ln56_fu_462_p2;
wire   [7:0] top_fu_468_p4;
wire   [0:0] icmp_ln57_fu_486_p2;
wire   [7:0] middle_fu_492_p4;
wire   [8:0] shl_ln1_fu_521_p3;
wire   [9:0] zext_ln76_fu_529_p1;
wire   [9:0] zext_ln74_3_fu_533_p1;
wire   [8:0] shl_ln3_fu_543_p3;
wire   [9:0] zext_ln79_2_fu_551_p1;
wire   [0:0] icmp_ln103_fu_561_p2;
wire   [31:0] add_ln103_fu_566_p2;
wire   [8:0] zext_ln74_1_fu_627_p1;
wire   [8:0] zext_ln74_fu_623_p1;
wire   [8:0] sub_ln74_fu_630_p2;
wire   [8:0] shl_ln76_1_fu_640_p3;
wire   [10:0] zext_ln74_2_fu_651_p1;
wire   [10:0] zext_ln76_3_fu_657_p1;
wire   [10:0] zext_ln76_1_fu_647_p1;
wire  signed [10:0] sext_ln76_fu_636_p1;
wire   [10:0] add_ln74_fu_666_p2;
wire   [10:0] sub_ln76_fu_660_p2;
wire   [8:0] shl_ln2_fu_678_p3;
wire   [10:0] zext_ln79_3_fu_693_p1;
wire   [10:0] zext_ln79_fu_686_p1;
wire   [8:0] zext_ln76_2_fu_654_p1;
wire   [8:0] sub_ln78_fu_702_p2;
wire  signed [10:0] sext_ln78_fu_708_p1;
wire   [10:0] sub_ln79_fu_696_p2;
wire   [10:0] add_ln78_fu_712_p2;
wire   [10:0] zext_ln79_1_fu_690_p1;
wire  signed [10:0] mul_ln81_fu_736_p0;
wire  signed [20:0] sext_ln81_fu_733_p1;
wire  signed [10:0] mul_ln81_fu_736_p1;
wire  signed [20:0] grp_fu_809_p3;
wire   [0:0] icmp_ln84_fu_745_p2;
wire   [7:0] outR_1_fu_750_p3;
wire   [7:0] outG_1_fu_757_p3;
wire   [7:0] outB_1_fu_764_p3;
wire   [7:0] outB_2_fu_783_p3;
wire   [7:0] outG_2_fu_777_p3;
wire   [7:0] outR_2_fu_771_p3;
wire   [7:0] grp_fu_800_p0;
wire   [3:0] grp_fu_800_p1;
wire   [13:0] grp_fu_800_p2;
wire  signed [10:0] grp_fu_809_p0;
wire  signed [10:0] grp_fu_809_p1;
reg    grp_fu_249_ce;
reg    grp_fu_800_ce;
reg    grp_fu_809_ce;
reg   [1:0] ap_NS_fsm;
reg    ap_condition_exit_pp0_iter6_stage0;
reg    ap_idle_pp0_0to5;
reg    ap_block_pp0;
reg    ap_enable_operation_90;
reg    ap_enable_state7_pp0_iter3_stage0;
reg    ap_enable_operation_107;
reg    ap_enable_state8_pp0_iter3_stage1;
reg    ap_predicate_op136_store_state9;
reg    ap_enable_operation_136;
reg    ap_enable_state9_pp0_iter4_stage0;
reg    ap_enable_operation_91;
reg    ap_enable_operation_108;
reg    ap_predicate_op138_store_state9;
reg    ap_enable_operation_138;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [23:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [2:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [2:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [23:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
wire   [55:0] grp_fu_249_p00;
wire   [11:0] grp_fu_800_p00;
wire   [40:0] grp_fu_800_p20;
wire   [13:0] mul_ln46_fu_340_p00;
reg    ap_condition_329;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

sobel_rgb_green_outline_fixed_sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_address0),
    .ce0(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_ce0),
    .we0(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_we0),
    .d0(gray_reg_967),
    .address1(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_address1),
    .ce1(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_ce1),
    .q1(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_q1)
);

sobel_rgb_green_outline_fixed_sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_address0),
    .ce0(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_ce0),
    .we0(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_we0),
    .d0(gray_reg_967),
    .address1(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_address1),
    .ce1(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_ce1),
    .q1(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_q1)
);

sobel_rgb_green_outline_fixed_mul_41ns_43ns_56_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 41 ),
    .din1_WIDTH( 43 ),
    .dout_WIDTH( 56 ))
mul_41ns_43ns_56_3_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_249_p0),
    .din1(grp_fu_249_p1),
    .ce(grp_fu_249_ce),
    .dout(grp_fu_249_p2)
);

sobel_rgb_green_outline_fixed_mul_8ns_7ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 14 ))
mul_8ns_7ns_14_1_1_U2(
    .din0(mul_ln46_fu_340_p0),
    .din1(mul_ln46_fu_340_p1),
    .dout(mul_ln46_fu_340_p2)
);

sobel_rgb_green_outline_fixed_mux_2_1_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_2_1_8_1_1_U3(
    .din0(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_q1),
    .din1(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_q1),
    .din2(trunc_ln35_fu_438_p1),
    .dout(top_fu_468_p4)
);

sobel_rgb_green_outline_fixed_mux_2_1_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_2_1_8_1_1_U4(
    .din0(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_q1),
    .din1(sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_q1),
    .din2(trunc_ln35_fu_438_p1),
    .dout(middle_fu_492_p4)
);

sobel_rgb_green_outline_fixed_mul_11s_11s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 21 ))
mul_11s_11s_21_1_1_U5(
    .din0(mul_ln81_fu_736_p0),
    .din1(mul_ln81_fu_736_p1),
    .dout(mul_ln81_fu_736_p2)
);

sobel_rgb_green_outline_fixed_mac_muladd_8ns_4ns_14ns_41_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 41 ))
mac_muladd_8ns_4ns_14ns_41_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_800_p0),
    .din1(grp_fu_800_p1),
    .din2(grp_fu_800_p2),
    .ce(grp_fu_800_ce),
    .dout(grp_fu_800_p3)
);

sobel_rgb_green_outline_fixed_mac_muladd_11s_11s_21s_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
mac_muladd_11s_11s_21s_21_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_809_p0),
    .din1(grp_fu_809_p1),
    .din2(mul_ln81_reg_1014),
    .ce(grp_fu_809_ce),
    .dout(grp_fu_809_p3)
);

sobel_rgb_green_outline_fixed_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 24 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 3 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 3 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 24 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 3 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_keep_V_reg_879_pp0_iter5_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 3 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_strb_V_reg_884_pp0_iter5_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_user_V_reg_889_pp0_iter5_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pix_last_V_reg_894_pp0_iter5_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

sobel_rgb_green_outline_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter4_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_fu_138 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0))) begin
        col_fu_138 <= col_2_fu_572_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((icmp_ln35_fu_272_p2 == 1'd0)) begin
            i_fu_134 <= i_2_fu_278_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_134 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_fu_142 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0))) begin
        row_fu_142 <= row_3_fu_579_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln35_reg_875 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        B_reg_899 <= {{in_stream_TDATA_int_regslice[23:16]}};
        G_reg_905 <= {{in_stream_TDATA_int_regslice[15:8]}};
        R_reg_912 <= R_fu_329_p1;
        in_pix_keep_V_reg_879 <= in_stream_TKEEP_int_regslice;
        in_pix_last_V_reg_894 <= in_stream_TLAST_int_regslice;
        in_pix_strb_V_reg_884 <= in_stream_TSTRB_int_regslice;
        in_pix_user_V_reg_889 <= in_stream_TUSER_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        B_reg_899_pp0_iter1_reg <= B_reg_899;
        B_reg_899_pp0_iter2_reg <= B_reg_899_pp0_iter1_reg;
        B_reg_899_pp0_iter3_reg <= B_reg_899_pp0_iter2_reg;
        B_reg_899_pp0_iter4_reg <= B_reg_899_pp0_iter3_reg;
        B_reg_899_pp0_iter5_reg <= B_reg_899_pp0_iter4_reg;
        G_reg_905_pp0_iter1_reg <= G_reg_905;
        G_reg_905_pp0_iter2_reg <= G_reg_905_pp0_iter1_reg;
        G_reg_905_pp0_iter3_reg <= G_reg_905_pp0_iter2_reg;
        G_reg_905_pp0_iter4_reg <= G_reg_905_pp0_iter3_reg;
        G_reg_905_pp0_iter5_reg <= G_reg_905_pp0_iter4_reg;
        R_reg_912_pp0_iter1_reg <= R_reg_912;
        R_reg_912_pp0_iter2_reg <= R_reg_912_pp0_iter1_reg;
        R_reg_912_pp0_iter3_reg <= R_reg_912_pp0_iter2_reg;
        R_reg_912_pp0_iter4_reg <= R_reg_912_pp0_iter3_reg;
        R_reg_912_pp0_iter5_reg <= R_reg_912_pp0_iter4_reg;
        and_ln73_reg_987_pp0_iter4_reg <= and_ln73_reg_987;
        and_ln73_reg_987_pp0_iter5_reg <= and_ln73_reg_987_pp0_iter4_reg;
        in_pix_keep_V_reg_879_pp0_iter1_reg <= in_pix_keep_V_reg_879;
        in_pix_keep_V_reg_879_pp0_iter2_reg <= in_pix_keep_V_reg_879_pp0_iter1_reg;
        in_pix_keep_V_reg_879_pp0_iter3_reg <= in_pix_keep_V_reg_879_pp0_iter2_reg;
        in_pix_keep_V_reg_879_pp0_iter4_reg <= in_pix_keep_V_reg_879_pp0_iter3_reg;
        in_pix_keep_V_reg_879_pp0_iter5_reg <= in_pix_keep_V_reg_879_pp0_iter4_reg;
        in_pix_last_V_reg_894_pp0_iter1_reg <= in_pix_last_V_reg_894;
        in_pix_last_V_reg_894_pp0_iter2_reg <= in_pix_last_V_reg_894_pp0_iter1_reg;
        in_pix_last_V_reg_894_pp0_iter3_reg <= in_pix_last_V_reg_894_pp0_iter2_reg;
        in_pix_last_V_reg_894_pp0_iter4_reg <= in_pix_last_V_reg_894_pp0_iter3_reg;
        in_pix_last_V_reg_894_pp0_iter5_reg <= in_pix_last_V_reg_894_pp0_iter4_reg;
        in_pix_strb_V_reg_884_pp0_iter1_reg <= in_pix_strb_V_reg_884;
        in_pix_strb_V_reg_884_pp0_iter2_reg <= in_pix_strb_V_reg_884_pp0_iter1_reg;
        in_pix_strb_V_reg_884_pp0_iter3_reg <= in_pix_strb_V_reg_884_pp0_iter2_reg;
        in_pix_strb_V_reg_884_pp0_iter4_reg <= in_pix_strb_V_reg_884_pp0_iter3_reg;
        in_pix_strb_V_reg_884_pp0_iter5_reg <= in_pix_strb_V_reg_884_pp0_iter4_reg;
        in_pix_user_V_reg_889_pp0_iter1_reg <= in_pix_user_V_reg_889;
        in_pix_user_V_reg_889_pp0_iter2_reg <= in_pix_user_V_reg_889_pp0_iter1_reg;
        in_pix_user_V_reg_889_pp0_iter3_reg <= in_pix_user_V_reg_889_pp0_iter2_reg;
        in_pix_user_V_reg_889_pp0_iter4_reg <= in_pix_user_V_reg_889_pp0_iter3_reg;
        in_pix_user_V_reg_889_pp0_iter5_reg <= in_pix_user_V_reg_889_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_875_pp0_iter1_reg == 1'd0))) begin
        add_ln46_1_reg_930 <= add_ln46_1_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0))) begin
        add_ln76_reg_994 <= add_ln76_fu_537_p2;
        add_ln79_reg_999 <= add_ln79_fu_555_p2;
        and_ln73_reg_987 <= and_ln73_fu_516_p2;
        gray_reg_967 <= {{grp_fu_249_p2[55:48]}};
        middle_3_reg_982 <= middle_3_fu_502_p3;
        top_3_reg_975 <= top_3_fu_478_p3;
        trunc_ln35_reg_963 <= trunc_ln35_fu_438_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_875_pp0_iter2_reg == 1'd0))) begin
        col_1_reg_957 <= col_1_fu_423_p2;
        icmp_ln73_reg_952 <= icmp_ln73_fu_417_p2;
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_addr_reg_940 <= zext_ln65_fu_398_p1;
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_addr_reg_946 <= zext_ln65_fu_398_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0))) begin
        gray_1_fu_166 <= {{grp_fu_249_p2[55:48]}};
        middle_2_fu_162 <= middle_3_fu_502_p3;
        p_0_0_01021_11421_fu_150 <= middle_2_fu_162;
        p_0_0_01021_21423_fu_154 <= gray_1_fu_166;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0))) begin
        gx_reg_1004 <= gx_fu_672_p2;
        gy_reg_1009 <= gy_fu_718_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln35_reg_875 <= icmp_ln35_fu_272_p2;
        icmp_ln35_reg_875_pp0_iter1_reg <= icmp_ln35_reg_875;
        icmp_ln35_reg_875_pp0_iter2_reg <= icmp_ln35_reg_875_pp0_iter1_reg;
        icmp_ln35_reg_875_pp0_iter3_reg <= icmp_ln35_reg_875_pp0_iter2_reg;
        icmp_ln35_reg_875_pp0_iter4_reg <= icmp_ln35_reg_875_pp0_iter3_reg;
        icmp_ln35_reg_875_pp0_iter5_reg <= icmp_ln35_reg_875_pp0_iter4_reg;
        mul_ln81_reg_1014 <= mul_ln81_fu_736_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0))) begin
        p_0_0_010211419_fu_146 <= top_2_fu_158;
        top_2_fu_158 <= top_3_reg_975;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == 1'b1) & (icmp_ln35_reg_875 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_875_pp0_iter5_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter6_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter6_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_134;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_249_ce = 1'b1;
    end else begin
        grp_fu_249_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_800_ce = 1'b1;
    end else begin
        grp_fu_800_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_809_ce = 1'b1;
    end else begin
        grp_fu_809_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == 1'b1) & (icmp_ln35_reg_875 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == 1'b1) & (icmp_ln35_reg_875 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_ce0 = 1'b1;
    end else begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_ce1 = 1'b1;
    end else begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln35_reg_963 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0))) begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_we0 = 1'b1;
    end else begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_ce0 = 1'b1;
    end else begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_ce1 = 1'b1;
    end else begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln35_reg_963 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0))) begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_we0 = 1'b1;
    end else begin
        sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to5 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter6_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_fu_309_p4 = {{in_stream_TDATA_int_regslice[23:16]}};

assign R_fu_329_p1 = in_stream_TDATA_int_regslice[7:0];

assign add_ln103_fu_566_p2 = (row_fu_142 + 32'd1);

assign add_ln46_1_fu_386_p2 = (grp_fu_800_p3 + zext_ln46_4_fu_382_p1);

assign add_ln74_fu_666_p2 = ($signed(zext_ln76_1_fu_647_p1) + $signed(sext_ln76_fu_636_p1));

assign add_ln76_fu_537_p2 = (zext_ln76_fu_529_p1 + zext_ln74_3_fu_533_p1);

assign add_ln78_fu_712_p2 = ($signed(sext_ln78_fu_708_p1) + $signed(sub_ln79_fu_696_p2));

assign add_ln79_fu_555_p2 = (zext_ln79_2_fu_551_p1 + zext_ln74_3_fu_533_p1);

assign and_ln73_fu_516_p2 = (icmp_ln73_reg_952 & icmp_ln56_fu_462_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_pp0 = (((1'b1 == ap_block_pp0_stage1_subdone) & (ap_ST_fsm_pp0_stage1 == ap_CS_fsm)) | ((1'b1 == ap_block_pp0_stage0_subdone) & (ap_ST_fsm_pp0_stage0 == ap_CS_fsm)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_stream_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) | ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_stream_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) | ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((out_stream_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((in_stream_TVALID_int_regslice == 1'b0) & (1'b1 == 1'b1) & (icmp_ln35_reg_875 == 1'd0)) | ((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((out_stream_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((in_stream_TVALID_int_regslice == 1'b0) & (1'b1 == 1'b1) & (icmp_ln35_reg_875 == 1'd0)) | ((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((out_stream_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((in_stream_TVALID_int_regslice == 1'b0) & (1'b1 == 1'b1) & (icmp_ln35_reg_875 == 1'd0)) | ((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)));
end

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_pp0_stage0_iter6 = (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1);
end

always @ (*) begin
    ap_block_state14_pp0_stage1_iter6 = (out_stream_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state15_pp0_stage0_iter7 = (out_stream_TREADY_int_regslice == 1'b0);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln35_reg_875 == 1'd0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_329 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_operation_107 = (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_108 = (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_136 = (ap_predicate_op136_store_state9 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_138 = (ap_predicate_op138_store_state9 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_90 = (icmp_ln35_reg_875_pp0_iter2_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_91 = (icmp_ln35_reg_875_pp0_iter2_reg == 1'd0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state7_pp0_iter3_stage0 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state8_pp0_iter3_stage1 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state9_pp0_iter4_stage0 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready_pp0_iter6_reg = 1'b0;

always @ (*) begin
    ap_predicate_op136_store_state9 = ((trunc_ln35_reg_963 == 1'd0) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op138_store_state9 = ((trunc_ln35_reg_963 == 1'd1) & (icmp_ln35_reg_875_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign col_1_fu_423_p2 = (col_fu_138 + 32'd1);

assign col_2_fu_572_p3 = ((icmp_ln103_fu_561_p2[0:0] == 1'b1) ? 32'd0 : col_1_reg_957);

assign grp_fu_249_p0 = grp_fu_249_p00;

assign grp_fu_249_p00 = add_ln46_1_reg_930;

assign grp_fu_249_p1 = 56'd2814749767107;

assign grp_fu_800_p0 = grp_fu_800_p00;

assign grp_fu_800_p00 = B_fu_309_p4;

assign grp_fu_800_p1 = 12'd11;

assign grp_fu_800_p2 = grp_fu_800_p20;

assign grp_fu_800_p20 = mul_ln46_fu_340_p2;

assign grp_fu_809_p0 = sext_ln81_1_fu_742_p1;

assign grp_fu_809_p1 = sext_ln81_1_fu_742_p1;

assign gx_fu_672_p2 = (add_ln74_fu_666_p2 + sub_ln76_fu_660_p2);

assign gy_fu_718_p2 = (add_ln78_fu_712_p2 - zext_ln79_1_fu_690_p1);

assign i_2_fu_278_p2 = (ap_sig_allocacmp_i_1 + 17'd1);

assign icmp_ln103_fu_561_p2 = ((col_1_reg_957 == 32'd320) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_272_p2 = ((ap_sig_allocacmp_i_1 == 17'd76800) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_462_p2 = (($signed(tmp_fu_452_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_486_p2 = (($signed(row_fu_142) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_417_p2 = (($signed(tmp_1_fu_407_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_745_p2 = ((grp_fu_809_p3 > 21'd48400) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign middle_3_fu_502_p3 = ((icmp_ln57_fu_486_p2[0:0] == 1'b1) ? middle_fu_492_p4 : 8'd0);

assign mul_ln46_fu_340_p0 = mul_ln46_fu_340_p00;

assign mul_ln46_fu_340_p00 = G_reg_905;

assign mul_ln46_fu_340_p1 = 14'd59;

assign mul_ln81_fu_736_p0 = sext_ln81_fu_733_p1;

assign mul_ln81_fu_736_p1 = sext_ln81_fu_733_p1;

assign outB_1_fu_764_p3 = ((icmp_ln84_fu_745_p2[0:0] == 1'b1) ? 8'd0 : B_reg_899_pp0_iter5_reg);

assign outB_2_fu_783_p3 = ((and_ln73_reg_987_pp0_iter5_reg[0:0] == 1'b1) ? outB_1_fu_764_p3 : B_reg_899_pp0_iter5_reg);

assign outG_1_fu_757_p3 = ((icmp_ln84_fu_745_p2[0:0] == 1'b1) ? 8'd255 : G_reg_905_pp0_iter5_reg);

assign outG_2_fu_777_p3 = ((and_ln73_reg_987_pp0_iter5_reg[0:0] == 1'b1) ? outG_1_fu_757_p3 : G_reg_905_pp0_iter5_reg);

assign outR_1_fu_750_p3 = ((icmp_ln84_fu_745_p2[0:0] == 1'b1) ? 8'd0 : R_reg_912_pp0_iter5_reg);

assign outR_2_fu_771_p3 = ((and_ln73_reg_987_pp0_iter5_reg[0:0] == 1'b1) ? outR_1_fu_750_p3 : R_reg_912_pp0_iter5_reg);

assign out_stream_TDATA_int_regslice = {{{outB_2_fu_783_p3}, {outG_2_fu_777_p3}}, {outR_2_fu_771_p3}};

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign row_3_fu_579_p3 = ((icmp_ln103_fu_561_p2[0:0] == 1'b1) ? add_ln103_fu_566_p2 : row_fu_142);

assign sext_ln46_fu_378_p1 = $signed(sub_ln46_fu_372_p2);

assign sext_ln76_fu_636_p1 = $signed(sub_ln74_fu_630_p2);

assign sext_ln78_fu_708_p1 = $signed(sub_ln78_fu_702_p2);

assign sext_ln81_1_fu_742_p1 = $signed(gy_reg_1009);

assign sext_ln81_fu_733_p1 = $signed(gx_reg_1004);

assign shl_ln1_fu_521_p3 = {{p_0_0_01021_11421_fu_150}, {1'd0}};

assign shl_ln2_fu_678_p3 = {{top_2_fu_158}, {1'd0}};

assign shl_ln3_fu_543_p3 = {{gray_1_fu_166}, {1'd0}};

assign shl_ln46_1_fu_361_p3 = {{R_reg_912_pp0_iter1_reg}, {1'd0}};

assign shl_ln76_1_fu_640_p3 = {{middle_3_reg_982}, {1'd0}};

assign shl_ln_fu_350_p3 = {{R_reg_912_pp0_iter1_reg}, {5'd0}};

assign sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_address0 = sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_addr_reg_940;

assign sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_1_address1 = zext_ln65_fu_398_p1;

assign sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_address0 = sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_addr_reg_946;

assign sobel_rgb_green_outline_fixed_stream_stream_axis_0_linebuf_address1 = zext_ln65_fu_398_p1;

assign sub_ln46_fu_372_p2 = (zext_ln46_fu_357_p1 - zext_ln46_1_fu_368_p1);

assign sub_ln74_fu_630_p2 = (zext_ln74_1_fu_627_p1 - zext_ln74_fu_623_p1);

assign sub_ln76_fu_660_p2 = (zext_ln74_2_fu_651_p1 - zext_ln76_3_fu_657_p1);

assign sub_ln78_fu_702_p2 = (zext_ln76_2_fu_654_p1 - zext_ln74_fu_623_p1);

assign sub_ln79_fu_696_p2 = (zext_ln79_3_fu_693_p1 - zext_ln79_fu_686_p1);

assign tmp_1_fu_407_p4 = {{col_fu_138[31:1]}};

assign tmp_fu_452_p4 = {{row_fu_142[31:1]}};

assign top_3_fu_478_p3 = ((icmp_ln56_fu_462_p2[0:0] == 1'b1) ? top_fu_468_p4 : 8'd0);

assign trunc_ln35_fu_438_p1 = row_fu_142[0:0];

assign zext_ln46_1_fu_368_p1 = shl_ln46_1_fu_361_p3;

assign zext_ln46_4_fu_382_p1 = $unsigned(sext_ln46_fu_378_p1);

assign zext_ln46_fu_357_p1 = shl_ln_fu_350_p3;

assign zext_ln65_fu_398_p1 = col_fu_138;

assign zext_ln74_1_fu_627_p1 = top_3_reg_975;

assign zext_ln74_2_fu_651_p1 = gray_reg_967;

assign zext_ln74_3_fu_533_p1 = p_0_0_01021_21423_fu_154;

assign zext_ln74_fu_623_p1 = p_0_0_010211419_fu_146;

assign zext_ln76_1_fu_647_p1 = shl_ln76_1_fu_640_p3;

assign zext_ln76_2_fu_654_p1 = gray_reg_967;

assign zext_ln76_3_fu_657_p1 = add_ln76_reg_994;

assign zext_ln76_fu_529_p1 = shl_ln1_fu_521_p3;

assign zext_ln79_1_fu_690_p1 = top_3_reg_975;

assign zext_ln79_2_fu_551_p1 = shl_ln3_fu_543_p3;

assign zext_ln79_3_fu_693_p1 = add_ln79_reg_999;

assign zext_ln79_fu_686_p1 = shl_ln2_fu_678_p3;


reg find_kernel_block = 0;
// synthesis translate_off
`include "sobel_rgb_green_outline_fixed_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //sobel_rgb_green_outline_fixed

