-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_object_green_classification_hls_object_green_classification_Pipeline_VITIS_LOOP_218_3_VITIS_LOOP_219_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    label_map_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    label_map_ce0 : OUT STD_LOGIC;
    label_map_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pixel_count_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    pixel_count_ce0 : OUT STD_LOGIC;
    pixel_count_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pixel_count_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    pixel_count_ce1 : OUT STD_LOGIC;
    pixel_count_we1 : OUT STD_LOGIC;
    pixel_count_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    max_y_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_y_ce0 : OUT STD_LOGIC;
    max_y_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    max_y_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_y_ce1 : OUT STD_LOGIC;
    max_y_we1 : OUT STD_LOGIC;
    max_y_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    min_y_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_y_ce0 : OUT STD_LOGIC;
    min_y_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    min_y_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_y_ce1 : OUT STD_LOGIC;
    min_y_we1 : OUT STD_LOGIC;
    min_y_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    max_x_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_x_ce0 : OUT STD_LOGIC;
    max_x_q0 : IN STD_LOGIC_VECTOR (8 downto 0);
    max_x_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    max_x_ce1 : OUT STD_LOGIC;
    max_x_we1 : OUT STD_LOGIC;
    max_x_d1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_x_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_x_ce0 : OUT STD_LOGIC;
    min_x_q0 : IN STD_LOGIC_VECTOR (8 downto 0);
    min_x_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    min_x_ce1 : OUT STD_LOGIC;
    min_x_we1 : OUT STD_LOGIC;
    min_x_d1 : OUT STD_LOGIC_VECTOR (8 downto 0) );
end;


architecture behav of hls_object_green_classification_hls_object_green_classification_Pipeline_VITIS_LOOP_218_3_VITIS_LOOP_219_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_12C00 : STD_LOGIC_VECTOR (16 downto 0) := "10010110000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_140 : STD_LOGIC_VECTOR (8 downto 0) := "101000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal icmp_ln218_reg_370 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln218_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal select_ln218_fu_228_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln218_reg_374 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln218_reg_374_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln218_1_fu_236_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln218_1_reg_383 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln218_1_reg_383_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal icmp_ln222_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln222_reg_398 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal min_x_addr_reg_402 : STD_LOGIC_VECTOR (8 downto 0);
    signal max_x_addr_reg_408 : STD_LOGIC_VECTOR (8 downto 0);
    signal min_y_addr_reg_414 : STD_LOGIC_VECTOR (8 downto 0);
    signal max_y_addr_reg_420 : STD_LOGIC_VECTOR (8 downto 0);
    signal pixel_count_addr_reg_426 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln223_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_reg_432 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln224_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln224_reg_436 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln225_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln225_reg_440 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln226_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln226_reg_444 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln221_3_fu_302_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln223_fu_313_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal x_fu_70 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_1_fu_244_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal y_fu_74 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten6_fu_78 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln218_fu_204_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln219_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_2_fu_216_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_265_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_276_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln221_fu_272_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln221_1_fu_283_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln221_fu_287_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln221_2_fu_293_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln221_1_fu_296_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hls_object_green_classification_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component hls_object_green_classification_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten6_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                indvar_flatten6_fu_78 <= ap_const_lv17_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln218_fu_198_p2 = ap_const_lv1_0))) then 
                indvar_flatten6_fu_78 <= add_ln218_fu_204_p2;
            end if; 
        end if;
    end process;

    x_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                x_fu_70 <= ap_const_lv9_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln218_fu_198_p2 = ap_const_lv1_0))) then 
                x_fu_70 <= x_1_fu_244_p2;
            end if; 
        end if;
    end process;

    y_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                y_fu_74 <= ap_const_lv8_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln218_fu_198_p2 = ap_const_lv1_0))) then 
                y_fu_74 <= select_ln218_1_fu_236_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln218_reg_370 <= icmp_ln218_fu_198_p2;
                select_ln218_1_reg_383_pp0_iter1_reg <= select_ln218_1_reg_383;
                select_ln218_reg_374_pp0_iter1_reg <= select_ln218_reg_374;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln218_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln222_reg_398 <= icmp_ln222_fu_307_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln222_reg_398 = ap_const_lv1_0))) then
                icmp_ln223_reg_432 <= icmp_ln223_fu_322_p2;
                icmp_ln224_reg_436 <= icmp_ln224_fu_327_p2;
                icmp_ln225_reg_440 <= icmp_ln225_fu_332_p2;
                icmp_ln226_reg_444 <= icmp_ln226_fu_337_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln218_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln222_fu_307_p2 = ap_const_lv1_0))) then
                max_x_addr_reg_408 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
                max_y_addr_reg_420 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
                min_x_addr_reg_402 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
                min_y_addr_reg_414 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
                pixel_count_addr_reg_426 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln218_fu_198_p2 = ap_const_lv1_0))) then
                select_ln218_1_reg_383 <= select_ln218_1_fu_236_p3;
                select_ln218_reg_374 <= select_ln218_fu_228_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln218_fu_204_p2 <= std_logic_vector(unsigned(indvar_flatten6_fu_78) + unsigned(ap_const_lv17_1));
    add_ln221_1_fu_296_p2 <= std_logic_vector(unsigned(add_ln221_fu_287_p2) + unsigned(zext_ln221_2_fu_293_p1));
    add_ln221_fu_287_p2 <= std_logic_vector(unsigned(zext_ln221_fu_272_p1) + unsigned(zext_ln221_1_fu_283_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, icmp_ln218_reg_370)
    begin
        if (((icmp_ln218_reg_370 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln218_fu_198_p2 <= "1" when (indvar_flatten6_fu_78 = ap_const_lv17_12C00) else "0";
    icmp_ln219_fu_222_p2 <= "1" when (x_fu_70 = ap_const_lv9_140) else "0";
    icmp_ln222_fu_307_p2 <= "1" when (label_map_q0 = ap_const_lv16_0) else "0";
    icmp_ln223_fu_322_p2 <= "1" when (unsigned(select_ln218_reg_374) < unsigned(min_x_q0)) else "0";
    icmp_ln224_fu_327_p2 <= "1" when (unsigned(select_ln218_reg_374) > unsigned(max_x_q0)) else "0";
    icmp_ln225_fu_332_p2 <= "1" when (unsigned(select_ln218_1_reg_383) < unsigned(min_y_q0)) else "0";
    icmp_ln226_fu_337_p2 <= "1" when (unsigned(select_ln218_1_reg_383) > unsigned(max_y_q0)) else "0";
    label_map_address0 <= zext_ln221_3_fu_302_p1(17 - 1 downto 0);

    label_map_ce0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            label_map_ce0 <= ap_const_logic_1;
        else 
            label_map_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    max_x_address0 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
    max_x_address1 <= max_x_addr_reg_408;

    max_x_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            max_x_ce0 <= ap_const_logic_1;
        else 
            max_x_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    max_x_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            max_x_ce1 <= ap_const_logic_1;
        else 
            max_x_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    max_x_d1 <= select_ln218_reg_374_pp0_iter1_reg;

    max_x_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, icmp_ln222_reg_398, icmp_ln224_reg_436)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln224_reg_436 = ap_const_lv1_1) and (icmp_ln222_reg_398 = ap_const_lv1_0))) then 
            max_x_we1 <= ap_const_logic_1;
        else 
            max_x_we1 <= ap_const_logic_0;
        end if; 
    end process;

    max_y_address0 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
    max_y_address1 <= max_y_addr_reg_420;

    max_y_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            max_y_ce0 <= ap_const_logic_1;
        else 
            max_y_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    max_y_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            max_y_ce1 <= ap_const_logic_1;
        else 
            max_y_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    max_y_d1 <= select_ln218_1_reg_383_pp0_iter1_reg;

    max_y_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, icmp_ln222_reg_398, icmp_ln226_reg_444)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln226_reg_444 = ap_const_lv1_1) and (icmp_ln222_reg_398 = ap_const_lv1_0))) then 
            max_y_we1 <= ap_const_logic_1;
        else 
            max_y_we1 <= ap_const_logic_0;
        end if; 
    end process;

    min_x_address0 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
    min_x_address1 <= min_x_addr_reg_402;

    min_x_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            min_x_ce0 <= ap_const_logic_1;
        else 
            min_x_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    min_x_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            min_x_ce1 <= ap_const_logic_1;
        else 
            min_x_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    min_x_d1 <= select_ln218_reg_374_pp0_iter1_reg;

    min_x_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, icmp_ln222_reg_398, icmp_ln223_reg_432)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln223_reg_432 = ap_const_lv1_1) and (icmp_ln222_reg_398 = ap_const_lv1_0))) then 
            min_x_we1 <= ap_const_logic_1;
        else 
            min_x_we1 <= ap_const_logic_0;
        end if; 
    end process;

    min_y_address0 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
    min_y_address1 <= min_y_addr_reg_414;

    min_y_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            min_y_ce0 <= ap_const_logic_1;
        else 
            min_y_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    min_y_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            min_y_ce1 <= ap_const_logic_1;
        else 
            min_y_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    min_y_d1 <= select_ln218_1_reg_383_pp0_iter1_reg;

    min_y_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, icmp_ln222_reg_398, icmp_ln225_reg_440)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln225_reg_440 = ap_const_lv1_1) and (icmp_ln222_reg_398 = ap_const_lv1_0))) then 
            min_y_we1 <= ap_const_logic_1;
        else 
            min_y_we1 <= ap_const_logic_0;
        end if; 
    end process;

    pixel_count_address0 <= zext_ln223_fu_313_p1(9 - 1 downto 0);
    pixel_count_address1 <= pixel_count_addr_reg_426;

    pixel_count_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pixel_count_ce0 <= ap_const_logic_1;
        else 
            pixel_count_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pixel_count_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pixel_count_ce1 <= ap_const_logic_1;
        else 
            pixel_count_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    pixel_count_d1 <= std_logic_vector(unsigned(pixel_count_q0) + unsigned(ap_const_lv16_1));

    pixel_count_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln222_reg_398)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln222_reg_398 = ap_const_lv1_0))) then 
            pixel_count_we1 <= ap_const_logic_1;
        else 
            pixel_count_we1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln218_1_fu_236_p3 <= 
        y_2_fu_216_p2 when (icmp_ln219_fu_222_p2(0) = '1') else 
        y_fu_74;
    select_ln218_fu_228_p3 <= 
        ap_const_lv9_0 when (icmp_ln219_fu_222_p2(0) = '1') else 
        x_fu_70;
    tmp_7_fu_276_p3 <= (select_ln218_1_reg_383 & ap_const_lv6_0);
    tmp_s_fu_265_p3 <= (select_ln218_1_reg_383 & ap_const_lv8_0);
    x_1_fu_244_p2 <= std_logic_vector(unsigned(select_ln218_fu_228_p3) + unsigned(ap_const_lv9_1));
    y_2_fu_216_p2 <= std_logic_vector(unsigned(y_fu_74) + unsigned(ap_const_lv8_1));
    zext_ln221_1_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_276_p3),17));
    zext_ln221_2_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln218_reg_374),17));
    zext_ln221_3_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln221_1_fu_296_p2),64));
    zext_ln221_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_265_p3),17));
    zext_ln223_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(label_map_q0),64));
end behav;
