// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="find_find,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.392000,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=25,HLS_SYN_LUT=192,HLS_VERSION=2023_1}" *)

module find (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OUT_VEC_din,
        OUT_VEC_full_n,
        OUT_VEC_write,
        IN_VEC_dout,
        IN_VEC_empty_n,
        IN_VEC_read,
        val_r
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] OUT_VEC_din;
input   OUT_VEC_full_n;
output   OUT_VEC_write;
input  [7:0] IN_VEC_dout;
input   IN_VEC_empty_n;
output   IN_VEC_read;
input  [7:0] val_r;

reg ap_idle;
reg[7:0] OUT_VEC_din;
reg OUT_VEC_write;
reg IN_VEC_read;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] icmp_ln13_reg_133;
reg   [0:0] icmp_ln17_1_reg_145;
reg    ap_predicate_op42_write_state4;
reg    ap_predicate_op44_write_state4;
reg   [0:0] icmp_ln13_1_reg_137;
reg    ap_predicate_op46_read_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_subdone;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    IN_VEC_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage0;
reg    OUT_VEC_blk_n;
reg   [0:0] icmp_ln17_reg_141;
reg   [0:0] icmp_ln17_2_reg_149;
reg   [0:0] icmp_ln17_3_reg_153;
reg   [7:0] val_r_read_reg_128;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln13_fu_92_p2;
wire   [0:0] icmp_ln13_1_fu_104_p2;
wire   [0:0] grp_fu_79_p2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state6_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg    ap_predicate_op35_write_state3;
reg    ap_predicate_op37_write_state3;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_11001;
reg    ap_block_pp0_stage3_11001;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [3:0] idx_fu_54;
wire   [3:0] add_ln13_fu_110_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_idx_1;
reg    ap_block_pp0_stage2_01001;
reg    ap_block_pp0_stage3_01001;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp0_stage1_01001;
wire   [3:0] or_ln13_fu_98_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_223;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

find_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_exit_pp0_iter0_stage3) | ((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if (((icmp_ln13_1_fu_104_p2 == 1'd1) & (icmp_ln13_fu_92_p2 == 1'd1))) begin
            idx_fu_54 <= add_ln13_fu_110_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            idx_fu_54 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln13_fu_92_p2 == 1'd1))) begin
        icmp_ln13_1_reg_137 <= icmp_ln13_1_fu_104_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln13_reg_133 <= icmp_ln13_fu_92_p2;
        val_r_read_reg_128 <= val_r;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        icmp_ln17_1_reg_145 <= grp_fu_79_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln13_1_reg_137 == 1'd1) & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        icmp_ln17_2_reg_149 <= grp_fu_79_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln17_3_reg_153 <= grp_fu_79_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln17_reg_141 <= grp_fu_79_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1) & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3) & (ap_predicate_op46_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        IN_VEC_blk_n = IN_VEC_empty_n;
    end else begin
        IN_VEC_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op46_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        IN_VEC_read = 1'b1;
    end else begin
        IN_VEC_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln17_3_reg_153 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln17_3_reg_153 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_2_reg_149 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_2_reg_149 == 1'd0)) | ((1'b0 == ap_block_pp0_stage3) & (ap_predicate_op44_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage3) & (ap_predicate_op42_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln17_reg_141 == 1'd0)) | ((1'b0 == ap_block_pp0_stage2) 
    & (icmp_ln13_reg_133 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln17_reg_141 == 1'd1)))) begin
        OUT_VEC_blk_n = OUT_VEC_full_n;
    end else begin
        OUT_VEC_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln17_3_reg_153 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_2_reg_149 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_01001) & (ap_predicate_op44_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_predicate_op37_write_state3 == 1'b1)))) begin
        OUT_VEC_din = 8'd1;
    end else if ((((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln17_3_reg_153 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_2_reg_149 == 1'd0)) | ((1'b0 == ap_block_pp0_stage3_01001) & (ap_predicate_op42_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_predicate_op35_write_state3 == 1'b1)))) begin
        OUT_VEC_din = 8'd0;
    end else begin
        OUT_VEC_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op44_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op42_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_predicate_op37_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_predicate_op35_write_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln17_3_reg_153 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln17_3_reg_153 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_2_reg_149 == 1'd1)) 
    | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_2_reg_149 == 1'd0)))) begin
        OUT_VEC_write = 1'b1;
    end else begin
        OUT_VEC_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & ((icmp_ln13_1_reg_137 == 1'd0) | (icmp_ln13_reg_133 == 1'd0)))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_idx_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_idx_1 = idx_fu_54;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_fu_110_p2 = (ap_sig_allocacmp_idx_1 + 4'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == IN_VEC_empty_n) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_2_reg_149 == 1'd1)) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_2_reg_149 == 1'd0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == IN_VEC_empty_n) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_2_reg_149 == 1'd1)) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_2_reg_149 == 1'd0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == IN_VEC_empty_n) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_2_reg_149 == 1'd1)) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_2_reg_149 == 1'd0))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((icmp_ln13_reg_133 == 1'd1) & (1'b0 == IN_VEC_empty_n) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == OUT_VEC_full_n) & (icmp_ln17_3_reg_153 == 1'd1)) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_3_reg_153 == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((icmp_ln13_reg_133 == 1'd1) & (1'b0 == IN_VEC_empty_n) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == OUT_VEC_full_n) & (icmp_ln17_3_reg_153 == 1'd1)) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_3_reg_153 == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((icmp_ln13_reg_133 == 1'd1) & (1'b0 == IN_VEC_empty_n) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == OUT_VEC_full_n) & (icmp_ln17_3_reg_153 == 1'd1)) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_3_reg_153 == 1'd0)))));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln13_reg_133 == 1'd1) & (1'b0 == IN_VEC_empty_n)) | ((1'b0 == OUT_VEC_full_n) & (ap_predicate_op37_write_state3 == 1'b1)) | ((1'b0 == OUT_VEC_full_n) & (ap_predicate_op35_write_state3 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln13_reg_133 == 1'd1) & (1'b0 == IN_VEC_empty_n)) | ((1'b0 == OUT_VEC_full_n) & (ap_predicate_op37_write_state3 == 1'b1)) | ((1'b0 == OUT_VEC_full_n) & (ap_predicate_op35_write_state3 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln13_reg_133 == 1'd1) & (1'b0 == IN_VEC_empty_n)) | ((1'b0 == OUT_VEC_full_n) & (ap_predicate_op37_write_state3 == 1'b1)) | ((1'b0 == OUT_VEC_full_n) & (ap_predicate_op35_write_state3 == 1'b1))));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op46_read_state4 == 1'b1) & (1'b0 == IN_VEC_empty_n)) | ((ap_predicate_op44_write_state4 == 1'b1) & (1'b0 == OUT_VEC_full_n)) | ((ap_predicate_op42_write_state4 == 1'b1) & (1'b0 == OUT_VEC_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op46_read_state4 == 1'b1) & (1'b0 == IN_VEC_empty_n)) | ((ap_predicate_op44_write_state4 == 1'b1) & (1'b0 == OUT_VEC_full_n)) | ((ap_predicate_op42_write_state4 == 1'b1) & (1'b0 == OUT_VEC_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op46_read_state4 == 1'b1) & (1'b0 == IN_VEC_empty_n)) | ((ap_predicate_op44_write_state4 == 1'b1) & (1'b0 == OUT_VEC_full_n)) | ((ap_predicate_op42_write_state4 == 1'b1) & (1'b0 == OUT_VEC_full_n))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln13_reg_133 == 1'd1) & (1'b0 == IN_VEC_empty_n));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = (((icmp_ln13_reg_133 == 1'd1) & (1'b0 == IN_VEC_empty_n)) | ((1'b0 == OUT_VEC_full_n) & (ap_predicate_op37_write_state3 == 1'b1)) | ((1'b0 == OUT_VEC_full_n) & (ap_predicate_op35_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = (((ap_predicate_op46_read_state4 == 1'b1) & (1'b0 == IN_VEC_empty_n)) | ((ap_predicate_op44_write_state4 == 1'b1) & (1'b0 == OUT_VEC_full_n)) | ((ap_predicate_op42_write_state4 == 1'b1) & (1'b0 == OUT_VEC_full_n)));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((1'b0 == IN_VEC_empty_n) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_2_reg_149 == 1'd1)) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_2_reg_149 == 1'd0)));
end

always @ (*) begin
    ap_block_state6_pp0_stage1_iter1 = (((1'b0 == OUT_VEC_full_n) & (icmp_ln17_3_reg_153 == 1'd1)) | ((1'b0 == OUT_VEC_full_n) & (icmp_ln17_3_reg_153 == 1'd0)));
end

always @ (*) begin
    ap_condition_223 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

always @ (*) begin
    ap_predicate_op35_write_state3 = ((icmp_ln13_reg_133 == 1'd1) & (icmp_ln17_reg_141 == 1'd0));
end

always @ (*) begin
    ap_predicate_op37_write_state3 = ((icmp_ln13_reg_133 == 1'd1) & (icmp_ln17_reg_141 == 1'd1));
end

always @ (*) begin
    ap_predicate_op42_write_state4 = ((icmp_ln17_1_reg_145 == 1'd0) & (icmp_ln13_reg_133 == 1'd1));
end

always @ (*) begin
    ap_predicate_op44_write_state4 = ((icmp_ln17_1_reg_145 == 1'd1) & (icmp_ln13_reg_133 == 1'd1));
end

always @ (*) begin
    ap_predicate_op46_read_state4 = ((icmp_ln13_1_reg_137 == 1'd1) & (icmp_ln13_reg_133 == 1'd1));
end

assign grp_fu_79_p2 = ((IN_VEC_dout == val_r_read_reg_128) ? 1'b1 : 1'b0);

assign icmp_ln13_1_fu_104_p2 = ((or_ln13_fu_98_p2 < 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_92_p2 = ((ap_sig_allocacmp_idx_1 < 4'd10) ? 1'b1 : 1'b0);

assign or_ln13_fu_98_p2 = (ap_sig_allocacmp_idx_1 | 4'd2);

endmodule //find
